### ISSUE TITLE
edit html

### ISSUE THREAD

**Issue by jay8t6** [miztroh/wysiwyg-e#101]
Can we get an option to enter HTML code into the editor? Right now it shows the read only mode and we cant modify the html.

**Comment by miztroh** [comment]
I have no plans to offer this as part of ``wysiwyg-e`` or its accompanying tools.  As its name suggests, this element is for what-you-see-is-what-you-get editing.  Direct editing of HTML the opposite of that.

That being said, I see no reason why you couldn't do one of the following:
* Create a custom tool.  Tools are sent an [update](https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L647) every time the value changes
* Create a tabbed interface that has ``wysiwyg-e`` in one tab's page and an HTML editor in the other tab's page

**Comment by jay8t6** [comment]
all I am asking for is to make the textarea editable when the edit html option from the settings icon is clicked. Its showing the source code, why not make it editable? Does it break anything? All of the open source editors like tinymce, and ckeditor has that feature.

**Comment by miztroh** [comment]
Glad you're trying the custom tool.  Making the read-only HTML view editable won't work because it's displaying a version that's been modified by syntax highlighting, etc.
