### ISSUE TITLE
create tags

### ISSUE THREAD

**Issue by jay8t6** [miztroh/wysiwyg-e#102]
Can you version your code so the releases are better handled?

**Comment by miztroh** [comment]
Indeed.  The goal is to resolve the open issues, then release 1.0.0 with semantic versioning from there on out.

**Comment by miztroh** [comment]
Additionally, the reason I haven't been doing semantic versioning yet is because I need to be free to change things drastically during these early stages of development.  The goal for the 1.0 release is that everything should be fairly stable.

**Comment by admwx7** [comment]
That's just for a 1.0 release once your API is fully stable, prior to a stable release when you're still in alpha you could be releasing 0.x in the meantime for people that want to use versioning in their apps before you've hit 1.0.

**Comment by miztroh** [comment]
I understand the desire for versioning.  1.0 should be released in the next week or so.

**Comment by miztroh** [comment]
@jay8t6 @admwx7 Happy v1.0.0!

**Comment by jay8t6** [comment]
Nice work! Thank you!
