### ISSUE TITLE
Space key bug

### ISSUE THREAD

**Issue by DominicWrege** [miztroh/wysiwyg-e#105]
The user can´t enter a new blank after a word because the cursor will jump to the beginning of the line.
 
http://d.pr/i/PN88

OS: Mac OS X 10.11.6
Browser: Google Chrome Version 52.0.2743.116 (64-bit)

**Comment by miztroh** [comment]
Confirmed.  Will address.

**Comment by miztroh** [comment]
@DominicWrege Can you confirm that this resolves the issue for you?

**Comment by DominicWrege** [comment]
@miztroh Yes!
