### ISSUE TITLE
Seems crash chrome on project with polymer 1.4.0

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#107]
I don't know if its really polymer 1.4.0 or related dependency but the demo crash chrome.

Updating polymer and all dependencies to latest resolved the problem

**Comment by miztroh** [comment]
Glad to know the latest version is working for you.  I've been developing using the latest version of Polymer.  Now that ``wysiwyg-e`` has a 1.0 release, I'm going to start specifying versions in the bower config.
