### ISSUE TITLE
Strange bug with editor when I try to toggle button

### ISSUE THREAD

**Issue by misterzorgy** [miztroh/wysiwyg-e#109]
When I toggle editor button my caret goes on the next line with letter I tried to pring
![ezgif-1734384828](https://cloud.githubusercontent.com/assets/4949934/18246568/1a131e70-7375-11e6-89d8-1774f324ef23.gif)

**Comment by miztroh** [comment]
Please provide a demo of this somewhere I can test it.

**Comment by miztroh** [comment]
Closing due to lack of response.  Feel free to reopen with a demo somewhere I can test.
