### ISSUE TITLE
Add option to have toolbar in a fixed position

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#11]
@miztroh thanks for your work on this.

**Comment by miztroh** [comment]
@chuckh No problem.  By "freeze", do you mean to disable the buttons and keyboard shortcuts?

**Comment by chuckh** [comment]
Do not mean disable buttons. I mean to lock the toolbar in place.  To have it in a fixed position.

like this: (green hello is fixed)
http://jsfiddle.net/austinbv/2KTFG/

**Comment by miztroh** [comment]
Wrapped the paper-toolbar in a paper-header-panel.  That should take care of it.  Thanks for the suggestion.
