### ISSUE TITLE
Add paste sanitization

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#111]
Open the word doc and copy and paste in the editor demo (after clear)

[Bonjour cousine.docx](https://github.com/miztroh/wysiwyg-e/files/480692/Bonjour.cousine.docx)

Now open the html view and you will see 

`<o:p class="style-scope wysiwyg-e"></o:p>` that is not xhtml valid.

**Comment by miztroh** [comment]
Yeah, you'll experience this issue and likely many more when pasting content from Word.  Currently, ``wysiwyg-e`` doesn't have any paste sanitization.  Will address.

**Comment by miztroh** [comment]
Fixed in the 2.0-preview branch.
