### ISSUE TITLE
Selection can be lost when clicking toolbar buttons

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#112]
Go to the demo and clear it.

Type a word.

Select the word with the mouse. and click multiple times on "italic". The mouse selection is lost. It shouldn't (test on word, ckeditor, tinyMCE)

**Comment by miztroh** [comment]
Confirmed.  Will address.

**Comment by miztroh** [comment]
@maxiplay Can you confirm this fixes the issue for you?

**Comment by miztroh** [comment]
@maxiplay Have you been able to test this on your end?

**Comment by maxiplay** [comment]
Sorry, I will say you it very soon (tonight)

**Comment by maxiplay** [comment]
Seems work on the demo but not on my local website. Need to investigate.

**Comment by maxiplay** [comment]
If you select a word and click looong time on bold the selection is lost.
