### ISSUE TITLE
Adding video seems does not work

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#114]
I tried to add this video 

https://www.youtube.com/watch?v=ytMqO-WQpQ4

But the video does not appear. Just a square

![capture](https://cloud.githubusercontent.com/assets/8363127/18642747/321d553e-7ea2-11e6-9474-e43bf1df34e4.PNG)

**Comment by miztroh** [comment]
That's because you're URL needs to be in this format: https://www.youtube.com/embed/ytMqO-WQpQ4.

**Comment by maxiplay** [comment]
Does not seems very convenient for normal user.

**Comment by miztroh** [comment]
Actually, this seems to not work either.  There's no intelligence built into the video player.  It's currently designed to work only with direct links to video files (e.g. mp4, ogg, etc.).

**Comment by maxiplay** [comment]
Is there a possible improvment in future releases ?

**Comment by miztroh** [comment]
Sure.  PRs welcome :)
