### ISSUE TITLE
Bold button bug (Alternate bold and unbold)

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#115]
Open the demo and clear it.

Type ddddd and click on bold. Type dddddd. Click on bold. Type ddddd. Strange behavior. The last text stay bold and a 'd' not bolded appear at the bottom

**Comment by maxiplay** [comment]
Same bug with others buttons

**Comment by miztroh** [comment]
Confirmed, but I think this is due to the selection bug.  Closing in favor of #112.
