### ISSUE TITLE
Small width view display bug

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#116]
![capture](https://cloud.githubusercontent.com/assets/8363127/18643317/dd7d83ac-7ea4-11e6-89ec-5919941751b7.PNG)

**Comment by maxiplay** [comment]
A little gift https://qlf-writecontrol.tk (alpha alpha version)

Don't be afraid by the "english" version. I will need a translator to have a good english.(French is better ;))

**Comment by miztroh** [comment]
Thanks for sending the URL.  Very cool to see ``wysiwyg-e`` out in the wild :)

**Comment by maxiplay** [comment]
:)

**Comment by miztroh** [comment]
I can't confirm this using Chrome on Windows 10.  Are you using the latest version?  Please provide your operating system and browser.

**Comment by maxiplay** [comment]
Version 53.0.2785.116 on windows 7.

**Comment by maxiplay** [comment]
Appear after manual resize down

**Comment by miztroh** [comment]
@maxiplay Can you confirm this fixes it?
