### ISSUE TITLE
Bulleted list from word bug

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#117]
Copy and paste the text from the word below.

Bulleted list seems not to behave correctly and cursor betwen line seems too to the left

[texte de test pour l'éditeur.docx](https://github.com/miztroh/wysiwyg-e/files/480810/texte.de.test.pour.l.editeur.docx)

![capture](https://cloud.githubusercontent.com/assets/8363127/18643972/b867fb9e-7ea7-11e6-8b93-a120bd0e248a.PNG)

With Ckeditor no problem.

http://ckeditor.com/demo

![image](https://cloud.githubusercontent.com/assets/8363127/18643934/912002ac-7ea7-11e6-85c6-37bad6dfb009.png)

**Comment by miztroh** [comment]
Closing in favor of #111.
