### ISSUE TITLE
Tools can get cut off in narrow mode if viewport is too short

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#118]
![test](https://cloud.githubusercontent.com/assets/2515209/18648064/8e9a886e-7e7e-11e6-9319-eedb2c24edc5.png)

**Comment by jpodwys** [comment]
I think it would be nice if they became vertically scrollable here and horizontally scrollable rather than wrapping on a wider screen.

**Comment by miztroh** [comment]
@jpodwys Thanks for the feedback.  I had considered this myself when working on the fix.  For now, the scroll is only available in narrow mode.  I prioritized this as a bug fix.  I will create a separate issue for the horizontal scroll as that is an enhancement, rather than a bug fix.

**Comment by miztroh** [comment]
@jpodwys See https://github.com/miztroh/wysiwyg-e/issues/123.

**Comment by jpodwys** [comment]
Thanks!
