### ISSUE TITLE
How manage translation ?

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#120]
Hello ! :)

I would like to provide a translation for button tooltip.

How can I do ?

**Comment by miztroh** [comment]
You'd probably want to look at doing it using Polymer's ``AppLocalizeBehavior``.

https://elements.polymer-project.org/elements/app-localize-behavior

**Comment by miztroh** [comment]
@maxiplay I have updated ``wysiwyg-e`` and its tools with support for Polymer's ``AppLocalizeBehavior``.  I've included the 'en' localizations for tooltips, labels, etc.  Each component manages its own ``resources`` object like the following:

```javascript
this.resources = {
	'en': {
		'Bold': 'Bold'
	}
};
```

You can add your own localizations as a one-off like this:

```
tool.set(
	'resources.fr',
	{
		'Bold': '<french word for bold>'
	}
);
```

Or, you could contribute your changes back to the project (e.g. https://github.com/miztroh/wysiwyg-e/blob/master/tools/bold.html#L28-L32).  ``wysiwyg-e.html`` and all the tool definition files have localizations.

Once you have localizations ready to go, just change the language property of your ``wysiwyg-e`` instance.  The change will propagate to the tools.

```html
<wysiwyg-e language="fr">
	<!-- Tools go here -->
</wysiwyg-e>

**Comment by maxiplay** [comment]
Nice job. i will obviously contribute :)

**Comment by miztroh** [comment]
Awesome.  If you'd like to go through all the files and provide corresponding French translations, that'd be great.  Just create an issue called "French localization" or something and then create a PR with a commit message of "Fixes #\<issue>".

**Comment by maxiplay** [comment]
I have been too speed. I do the work before you give me intructions.
