### ISSUE TITLE
Conversion into markdown

### ISSUE THREAD

**Issue by jwillmer** [miztroh/wysiwyg-e#124]
I really like the editor but to store the content and to easily transform it to other formats it would be cool to have a way of transforming it to markdown. Could you advice me if there is a easy/good solution for this or if this would turn out to be a seperate component?

**Comment by aloscha** [comment]
If we establish that each paragraph could have just one heading, than editor makes sense for that usage.

**Comment by miztroh** [comment]
While I agree that markdown conversion can be a very useful feature, I don't think it would be appropriate to bundle an HTML-to-markdown converter with ``wysiwyg-e``.  It would add bloat for users that don't need that functionality and code complexity for me in terms of trying to support markdown compatibility for all the various content types the editor supports (audio, video, etc.).

However, it would be relatively easy to do this yourself using an HTML-to-markdown converter like the one listed below along with the following pattern:

https://github.com/domchristie/to-markdown

```html
<dom-module id="wysiwyg-html-to-markdown">
  <template>
    <wysiwyg-e value="{{html}}">
      <content></content>
    </wysiwyg-e>
  </template>
  <script>
    Polymer(
      {
        is: 'wysiwyg-html-to-markdown',
        properties: {
          html: {
            type: String
          },
          markdown: {
            type: String,
            computed: '_computeMarkdown(html, options.*)'
          },
          //See documentation at https://github.com/domchristie/to-markdown
          options: {
            type: String,
            value: function () {
              return {};
            }
          }
        },
        _computeMarkdown: function (html) {
          return toMarkdown(html, this.options);
        }
      }
    );
  </script>
</dom-module>
```

Then you'd use this element in place of ``wysiwyg-e``.

```html
<wysiwyg-html-to-markdown html="{{html}}" markdown="{{markdown}}">
  <!-- tools go here -->
</wysiwyg-html-to-markdown>
```
