### ISSUE TITLE
Selection bug 

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#128]
Hello,

When I select a word and I stay click on button with light right mouvement the selection is lost.

I published a vidéo.

[video](https://drive.google.com/file/d/0Bz9a1ywlc9N8cktrSEdnNnRPZVk/view)

**Comment by maxiplay** [comment]
New equivalent bug.

Remove all content. Type a word and select it. Click lot of time on button and the selection is lost.

[video](https://drive.google.com/file/d/0Bz9a1ywlc9N8X2tGR3VWUk04SUU/view )

**Comment by maxiplay** [comment]
Equivalent bug when set manually simple value

[video](https://drive.google.com/file/d/0Bz9a1ywlc9N8UXYtVHk3bFIyN2M/view)

**Comment by miztroh** [comment]
@maxiplay Thanks for the videos.  I believe I've resolved this.  Please test this on your end and let me know how it goes for you.

**Comment by miztroh** [comment]
@maxiplay Can you confirm this fixes things for you?

**Comment by maxiplay** [comment]
Seems good :+1:
