### ISSUE TITLE
Custom icon sets

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#134]
Use a custom icon set for ``wysiwyg-e`` and each of the tools and avoid loading multiple sets of ``iron-icons``.

**Comment by maxiplay** [comment]
Have You watched the polymer stream live about performance ? ^^

**Comment by miztroh** [comment]
Yeah, that's what made me think about doing a performance review.  I'm nearly done with the custom icon sets.  However, most of the other performance improvements suggested are end user improvements (only loading polyfills if required, async loading polyfills and imports, etc.).  HTTP2 stuff is obviously up to the the host of any projects using ``wysiwyg-e``.  Custom icon sets are something I can control.  I can also improve performance of the DOM mutation observer (from https://github.com/miztroh/selection-mgr) and sanitize function (ala #137).
