### ISSUE TITLE
Editor Performance

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#137]
It seems that the more text, more is slow. Lot of other editors are like this but I think we could do better.

It seems the rendering is applied for all content each time I type a character. We could use a sort of incremental rendering.

This editors seems have a better behavior with large text => 

[froala](https://froala.com/wysiwyg-editor)

[medium](https://yabwe.github.io/medium-editor/demo.html)

[quilljs](http://quilljs.com/)

See the video.

[Video](https://drive.google.com/file/d/0Bz9a1ywlc9N8aFJFTWRHdlRJdHM/view)

**Comment by maxiplay** [comment]
A interesting list of the wysiwig eco system

https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md

**Comment by miztroh** [comment]
Closing in favor of #150.
