### ISSUE TITLE
Ctrl+Backspace to delete an entire word

### ISSUE THREAD

**Issue by aletorrado** [miztroh/wysiwyg-e#140]
I don't know why this isn't working, given that `wysiwyg-e` relies on `contenteditable`. It would be nice to fix this. Do you think it possible?

**Comment by miztroh** [comment]
While it ``wysiwyg-e`` does make use of a ``contenteditable`` target, many of the common key bindings have their default actions prevented.  This is to allow ``wysiwyg-e`` and individual tools to manage their own key bindings.  As such, this would be an enhancement.  I have no objection to adding this functionality.

**Comment by miztroh** [comment]
This is fixed in the 2.0-preview branch.
