### ISSUE TITLE
User interaction change event

### ISSUE THREAD

**Issue by aletorrado** [miztroh/wysiwyg-e#141]
It would be nice to have an event fired when `value` have changed because of user interaction, just like `paper-input` do. I could attach an observer to the value property but I wouldn't disguise if it's because of user input or not.

**Comment by miztroh** [comment]
http://miztroh.github.io/bower_components/wysiwyg-e/#wysiwyg-e:property-value

The ``value`` property already notifies via a ``value-changed`` event.  You can listen for that.

**Comment by aletorrado** [comment]
I need to get notified only of changes made by user interaction (not when modifying the `value` property programatically). This is accomplished in `paper-input` using a change event.

This is how `paper-input` defines the `change` event:

```
change
Fired when the input changes due to user interaction.
```
