### ISSUE TITLE
Dynamicaly change language seems does not work

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#142]
It works when component is started but not when you programmatically change the language property with databinding

**Comment by miztroh** [comment]
Can you provide a demo?  I can't confirm this.  The following works for me to switch to French and back:

``$('wysiwyg-e').language = 'fr';``
``$('wysiwyg-e').language = 'en';``

**Comment by maxiplay** [comment]
Ok I will provide very soon

**Comment by maxiplay** [comment]
I create a special branch (languageTester) in my repo. After test it seems working. I need to investigate in my app. Sorry.

**Comment by maxiplay** [comment]
Indeed I had a carriage return in my language variable not visible in chrome debugguer. So "fr" is not equal to "fr\n" and the translation does not work.

**Comment by miztroh** [comment]
Glad to hear you got it resolved.
