### ISSUE TITLE
How to use it with polymer cli?

### ISSUE THREAD

**Issue by MarcosGalaviz** [miztroh/wysiwyg-e#144]
Hi thank you so much for your component, I am triying to use it inside a component with the new polymer cli but i can't do it, which is the best way to do that?

Thanks a lot.

**Comment by miztroh** [comment]
Can you be more specific?  As long as you're importing the element definition file for ``wysiwyg-e`` and any of the tools you're trying to use (bold, etc.), you should be able to use it just like README.md file indicates:

```html
<wysiwyg-e>
  <wysiwyg-tool-bold></wysiwyg-tool-bold>
  <wysiwyg-tool-italic></wysiwyg-tool-italic>
  <wysiwyg-tool-underline></wysiwyg-tool-underline>
  <wysiwyg-tool-strike></wysiwyg-tool-strike>
  <wysiwyg-tool-clear></wysiwyg-tool-clear>
  <wysiwyg-tool-code></wysiwyg-tool-code>
  <wysiwyg-tool-link></wysiwyg-tool-link>
  <wysiwyg-tool-image></wysiwyg-tool-image>
  <wysiwyg-tool-audio></wysiwyg-tool-audio>
  <wysiwyg-tool-video></wysiwyg-tool-video>
  <wysiwyg-tool-ordered></wysiwyg-tool-ordered>
  <wysiwyg-tool-unordered></wysiwyg-tool-unordered>
  <wysiwyg-tool-indent></wysiwyg-tool-indent>
  <wysiwyg-tool-outdent></wysiwyg-tool-outdent>
  <wysiwyg-tool-justify right center full></wysiwyg-tool-justify>
  <wysiwyg-tool-heading h1 h2 h3 h4 h5 h6></wysiwyg-tool-heading>
  <wysiwyg-tool-blockquote></wysiwyg-tool-blockquote>
  <wysiwyg-tool-undo></wysiwyg-tool-undo>
  <wysiwyg-tool-redo></wysiwyg-tool-redo>
</wysiwyg-e>
```

**Comment by MarcosGalaviz** [comment]
Sorry I was using it wrong [😊]   it would be nice to can change the color of the font [😃]


Thanks

________________________________
De: Jonathan Cox <notifications@github.com>
Enviado: miércoles, 7 de diciembre de 2016 08:00:37 p. m.
Para: miztroh/wysiwyg-e
Cc: MarcosGalaviz; Author
Asunto: Re: [miztroh/wysiwyg-e] How to use it with polymer cli? (#144)


Can you be more specific? As long as you're importing the element definition file for wysiwyg-e and any of the tools you're trying to use (bold, etc.), you should be able to use it just like README.md file indicates:

<wysiwyg-e>
  <wysiwyg-tool-bold></wysiwyg-tool-bold>
  <wysiwyg-tool-italic></wysiwyg-tool-italic>
  <wysiwyg-tool-underline></wysiwyg-tool-underline>
  <wysiwyg-tool-strike></wysiwyg-tool-strike>
  <wysiwyg-tool-clear></wysiwyg-tool-clear>
  <wysiwyg-tool-code></wysiwyg-tool-code>
  <wysiwyg-tool-link></wysiwyg-tool-link>
  <wysiwyg-tool-image></wysiwyg-tool-image>
  <wysiwyg-tool-audio></wysiwyg-tool-audio>
  <wysiwyg-tool-video></wysiwyg-tool-video>
  <wysiwyg-tool-ordered></wysiwyg-tool-ordered>
  <wysiwyg-tool-unordered></wysiwyg-tool-unordered>
  <wysiwyg-tool-indent></wysiwyg-tool-indent>
  <wysiwyg-tool-outdent></wysiwyg-tool-outdent>
  <wysiwyg-tool-justify right center full></wysiwyg-tool-justify>
  <wysiwyg-tool-heading h1 h2 h3 h4 h5 h6></wysiwyg-tool-heading>
  <wysiwyg-tool-blockquote></wysiwyg-tool-blockquote>
  <wysiwyg-tool-undo></wysiwyg-tool-undo>
  <wysiwyg-tool-redo></wysiwyg-tool-redo>
</wysiwyg-e>

**Comment by miztroh** [comment]
@MarcosGalaviz ``wysiwyg-e`` supports a lot of CSS custom properties.  Check out the full list via the link below:

https://miztroh.github.io/bower_components/wysiwyg-e/
