### ISSUE TITLE
Code Tool Is Not Working Correctly 

### ISSUE THREAD

**Issue by hyyan** [miztroh/wysiwyg-e#145]
Hello @miztroh 

Thanks again for this awesome work .

The main issue I am facing currently that I need the code tool to work as users would expect from such a tool , but unfortunately it is not , I have created my own fork of this project and my own code tool , but 
I don like the idea of maintaining my own fork of this project as every time I sync the fork with the master brunch  I get new problems and it became really annoying to keep doing this ,

I have tried also to send a PR but it was not accpeted as it modifies the [sanitize method](https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L654) 

** The Problem ** 
- Creating a new code block creates a new `pre-code` around every line and the code tool can not handle code formatted with code tag only 
- Can not create code block from exiting text , the text will be removed then an empty block is created 
- Can not use tabs inside code blocks , the editor will create blockquote directly 
- The clear command does not clean the code block around the text ,the text is just moved out of the node and the code block is kept

I guess the whole problem related to code blocks are coming from the sanitize function in [here](https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L670-L708)

I still can not get my head around these lines , why are they needed 

Thanks in advance

**Comment by miztroh** [comment]
@hyyan:  I've resolved this issue as noted below.

- The code tool now uses only a single ``code`` tag (no ``pre``).
- You can now create code blocks from selected text
- The tabbing issue is not specific to the code tool.  I have opened https://github.com/miztroh/wysiwyg-e/issues/158 to track a resolution on this.
- The clear tool now removes the code element as expected.

Thanks for your patience.  I've been hard at work trying to get this ready for the Polymer 2.0 release.

**Comment by hyyan** [comment]
@miztroh Thanks for your awesome work, I will try to test your new changes tomorrow , and if there are any bugs left, I will report 😄 

Keep it up 🍺
