### ISSUE TITLE
Not working with Meteor?

### ISSUE THREAD

**Issue by EliArtist** [miztroh/wysiwyg-e#146]
I tried to use wysiswyg-e within my Meteor/Polymer Application, but get the Error

> Uncaught ReferenceError: keyboardeventKeyPolyfill is not defined

I just used <wysiwyg-e></wysiwyg-e> in my Code without any Tools or additional attributes.
I imported wysiwig-e.html, wysiwyg-tools-behavior.html and wysiwyg-tool-styles.html

**Comment by miztroh** [comment]
Check dev tools for a network request to ``bower_components/keyboardevent-key-polyfill/index.js``.  If that request doesn't complete, you'll get that error.

**Comment by EliArtist** [comment]
Seems like the keyboardevent-key-polyfill library is causing the problem with Meteor.
I can avoid the error, when deleting the loader in `bower_components/keyboardevent-key-polyfill/index.js`, but now, I'm getting the error `Undo is not defined`. Working on it.

**Comment by miztroh** [comment]
Looks like I'll be able to phase out this polyfill over the next several months.  In the meantime, I'm not sure how much help I can be in terms of troubleshooting loading of required files in Meteor.  If you're project only needs to work in the browsers with KeyboardEvent.key support (see link below), then you can just replace the polyfill's index.js with a blank script.

http://caniuse.com/?feat=keyboardevent-key#search=keyboardevent.key
