### ISSUE TITLE
Editor Validation 

### ISSUE THREAD

**Issue by hyyan** [miztroh/wysiwyg-e#152]
Hello 

Is is possible to handle editor validation , currently I can  not detect if editor is empty or not , the value of editor in case it is empty always equals to `<p class="style-scope wysiwyg-e"><br class="style-scope wysiwyg-e"></p>`

Is there an event or something like `paper-input` event `change` 

Thanks in advance

**Comment by miztroh** [comment]
This will be resolved in the 2.x release.  I have added a 'text' property to ``undo-mgr`` (a ``wysiwyg-e`` dependency).  See https://github.com/miztroh/undo-mgr/commit/6e16ec7bf7129eed4d489cf6c67431a3c8eb43e5.  Once 2.x is released, you'll be able to do something like this for validation:

```javascript
if (wysiwygE_instance.text.length === 0) {
   //perhaps with trim() to ensure that it's not just a bunch of whitespace
}
```

Note that this approach only helps you check for text content.  It would still be possible to have nodes with no text content (like the P node you mentioned).
