### ISSUE TITLE
Inconsistency in styling documentation

### ISSUE THREAD

**Issue by mmnosek** [miztroh/wysiwyg-e#153]
Just spent some time finding out why toolbar background color styling doesn't work. Documentation is not valid for the actual code:

**In documentation:**
`wysiwyg-toolbar-background-color`

**In code:**
`wysiwyg-toolbar-background`

**Comment by miztroh** [comment]
Good catch.  I've resolved this in the 2.0-preview branch.

**Comment by mmnosek** [comment]
Thanks for fixing and your awesome work!
