### ISSUE TITLE
Unable to paste in the video/image form

### ISSUE THREAD

**Issue by jpicus** [miztroh/wysiwyg-e#155]
Hello.

It works fine for me, except i'm unable to paste and image or video url in the form opened via the corresponding toolbar button.

Any clues ? 

Thanks

**Comment by miztroh** [comment]
I'm not able to confirm this in Chrome.  What OS / browser are you using (include versions).

**Comment by jpicus** [comment]
It was a problem linked to the "shady" mode 
Went back to shadow mode solved the problem
