### ISSUE TITLE
Wysiwyg-e does not work when Shadow DOM polyfill is enabled

### ISSUE THREAD

**Issue by warpech** [miztroh/wysiwyg-e#156]
When I change `webcomponents-lite.min.js` to `webcomponents.min.js` in `demo/index.html` (meaning: enable Shadow DOM polyfill), the demo does not work in Firefox and other polyfilled browsers.

![bug](https://cloud.githubusercontent.com/assets/566463/22101176/9a52d062-de32-11e6-811c-283722cc8a95.gif)

**Comment by miztroh** [comment]
Looks like there are issues with the Shadow DOM polyfill and ``contenteditable`` nodes.  Unless I'm missing something, I'll close this as a won't-fix.

**Comment by miztroh** [comment]
For your reference:

https://github.com/webcomponents/webcomponentsjs#execcommand

**Comment by warpech** [comment]
Perhaps the solution is to put the `contenteditable` node in light DOM, not in Shadow DOM? 

This custom element is lovely, but if it is not compatible with Shadow DOM polyfill, then it misses the most common use case.
