### ISSUE TITLE
Proposal: Add a placeholder

### ISSUE THREAD

**Issue by abdonrd** [miztroh/wysiwyg-e#161]
Like the `input` or `textarea` elements, add a placeholder:

`placeholder`: A hint to the user of what can be entered in the control. The placeholder text must not contain carriage returns or line-feeds. 

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by miztroh** [comment]
Care to add a description of what you're asking for?

**Comment by abdonrd** [comment]
Sorry, I thought the title was clear. Updated

**Comment by miztroh** [comment]
Sure, but what are you wanting me to add a placeholder ***to***?

**Comment by abdonrd** [comment]
To the `wysiwyg-e`.

**Comment by miztroh** [comment]
I don't know how that would work.  ``wysiwyg-e`` is never empty.  Even if you set its value to an empty string, it will repopulate with the following:

```html
<p>
   <br>
</p>
```

**Comment by miztroh** [comment]
If that was unclear, I meant that you would never see a placeholder even if I added one because ``wysiwyg-e`` is never empty.

**Comment by abdonrd** [comment]
Thank you, I understood.
But why not show a placeholder when the content is:

```html
<p>
   <br>
</p>
```

**Comment by miztroh** [comment]
Don't placeholders only appear when there is no content?

**Comment by abdonrd** [comment]
Yes, but if you set the "empty status" as `<p><br></p>` I think is ok.

**Comment by miztroh** [comment]
Added a ``placeholder`` string property, a ``showPlaceholder`` computed property, and a ``--wysiwyg-editable-placeholder`` CSS mixin.  Thanks for the suggestion.
