### ISSUE TITLE
Shady or Shadow

### ISSUE THREAD

**Issue by jpicus** [miztroh/wysiwyg-e#163]
We have Polymer global behaviou set on "shadow" mode 
(      // Setup Polymer options
      window.Polymer = {
         dom: 'shadow',
...)

Maybe not related, but It seems that wysiwyg-e has some issues with this configuration ?
- unable to paste something copied from "outsite wysiwyg-e"
- when opening the image selector, nothing happens when clicking on the validataion or cancle buttons

Any clues ?

**Comment by miztroh** [comment]
The shady / shadow issue likely doesn't apply anymore as I've merged my 2.0-preview code into master to work with Polymer 2.0.  Please open separate issues for other items.
