### ISSUE TITLE
Issue with URL and delete

### ISSUE THREAD

**Issue by jerryeventjoy** [miztroh/wysiwyg-e#167]
Thank you for creating this module.
I have integrated this module into our dashboard and successfully read and write values from and to our database.  I assumed all options to work right out of the box.  Unfortunately, I am having issues around adding URL and deleting characters.  

URL issue:  After I select word to add URL, clicking on URL button would loose selection and the form would turn into red.  

Delete issue: When I delete a character, sometimes it would delete one character, but every other time, it would delete two or more characters.  I am not sure what is causing this kind of behavior.

There are other formatting issues like adding unordered list.  It would add list icon in front of other lines.  For now, I am getting around this issue by putting input indicator at the end of a line, then it would add icon at the front.  

Please review and let me know what your thoughts are.  If you need to review my code, I can provide snippet as needed.

Thanks.

**Comment by miztroh** [comment]
Please submit individual GitHub issues for each problem, along with steps to reproduce and information as to your operating system and browser.  Thanks!
