### ISSUE TITLE
pasting is inconsistent with rich input

### ISSUE THREAD

**Issue by Juravenator** [miztroh/wysiwyg-e#168]
For my example, I copied some text from [Cupcake Ipsum](http://www.cupcakeipsum.com/).

When I paste this text first into a plain text editor, which parses it into plain text, and then into wysiwys-e, everything works as expected.
That is, the pasted content is visible to the user and the `value` property is updated.

However, when I paste the formatted text, the content of the editor changes, but the `value` property is not updated.

![image](https://cloud.githubusercontent.com/assets/6351374/24453391/e905f49c-1487-11e7-8f72-3a53e4d8255f.png)

**Comment by Juravenator** [comment]
PS: typing something after pasting does set the `value` property to what the user would expect

**Comment by miztroh** [comment]
The above commit should resolve the issue for you.  Thanks for the report!
