### ISSUE TITLE
tool paper-menu-buttons: focus issues in paper-input

### ISSUE THREAD

**Issue by Juravenator** [miztroh/wysiwyg-e#170]
Tools that implement dropdown content, such as:
- `wysiwyg-tool-link`
- `wysiwyg-tool-justify`
- `wysiwyg-tool-justify`

don't function in Polymer 2, it seems the controls in them can't be clicked.
The only exception to this pattern is `wysiwyg-tool-color`, which seems to work fine.

**Comment by miztroh** [comment]
Sorry for the early close.  I did resolve one issue where the dropdowns weren't opening.  This was related to slot changes in ``paper-menu-button``.  However, I am still experiencing the issue where the contents of those dropdowns aren't accessible via click.

**Comment by miztroh** [comment]
Still in-progress, but I fixed the ``paper-menu-dropdown`` slotting issue.

https://github.com/miztroh/wysiwyg-e/commit/5f7edc3dc20cd25ae7745f1d824e6e75fd871cec

**Comment by miztroh** [comment]
Still in-progress, but I fixed the ``paper-item`` styling issue.

https://github.com/miztroh/wysiwyg-e/commit/806200fa10541ad159cadd4db5ab852696a861ec

**Comment by miztroh** [comment]
Updated title to narrow scope to ``paper-menu-button`` -> ``paper-input``.  The ``paper-item`` issue is caused by something else.  See https://github.com/miztroh/wysiwyg-e/issues/172.
