### ISSUE TITLE
Youtube Link

### ISSUE THREAD

**Issue by Daniel-Gherard** [miztroh/wysiwyg-e#174]
I think it would be amazing to have a Youtube button to add a url and show Youtube videos in the editor.

**Comment by miztroh** [comment]
I will accept a PR for this :) ``wysiwyg-e`` has been designed from the ground up to support custom tools.  In the 2.0 (pre) release, there's a ``WysiwygTool`` class you can extend.  Check out the code for any of the current tools to see how this is done.

**Comment by Daniel-Gherard** [comment]
Ok. I'll do a PR then. Very good job on the component.
