### ISSUE TITLE
position and size

### ISSUE THREAD

**Issue by KhanaevRoman** [miztroh/wysiwyg-e#175]
Good day!
How can I hold toolbar on the top of editor **in any width** and make toolbar icons **smaller**?

With respect, Roman.

**Comment by miztroh** [comment]
You can set the ``forceWide`` property to ``true`` to keep the toolbar on top.  The toolbar is configured to let you scroll the toolbar buttons left and right if they can't all fit.  I am not interested in making the icons any smaller, as that will negatively impact touch interactions.

**Comment by KhanaevRoman** [comment]
Ok, thank you
