### ISSUE TITLE
Youtube URLs doesn't work in the video tool

### ISSUE THREAD

**Issue by phani1kumar** [miztroh/wysiwyg-e#178]
Firstly, Thank you very much for such a wonderful component. 

I tried to use the Youtube links inside the video URLs and nothing comes up. Should I host the videos myself and provide the URLs?

**Comment by miztroh** [comment]
This is not currently a feature of the video tool.  Currently, the video tool provides very basic functionality.  You give it a URL and it creates an HTML5 video element with the given URL as its source.  It would probably be best to create a separate tool for use with YouTube.  I will happily accept PRs for this.
