### ISSUE TITLE
v1.1.0 dependency issue with selection-mgr

### ISSUE THREAD

**Issue by samsinha** [miztroh/wysiwyg-e#179]
Hello,

This issue is regarding `wysiwyg-e v1.1.0`.

It looks like `wysiwyg-e v1.1.0` has a dependency - `"selection-mgr": "miztroh/selection-mgr#latest"` as listed in bower.json. 

selection-mgr#latest pulls down selection-mgr v2.0.0. 

However, in `wysiwyg-e.html`, it's trying to import `<link rel="import" href="../selection-mgr/behavior.html">` which does not exist in v2.0.0 of selection-mgr.

This is causing a build failure, since my app is still on Polymer 1.x and depends on `wysiwyg-e v1.1.0`.

**Comment by miztroh** [comment]
Check out release 1.1.2.

**Comment by samsinha** [comment]
Thanks for the quick turnaround on this.
