### ISSUE TITLE
Intermittent loss of selection when clicking tool buttons

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#180]
Hey ! I quiclky tested demo here https://www.webcomponents.org/element/miztroh/wysiwyg-e

and a selection problem occur 

See [video](https://drive.google.com/file/d/0Bz9a1ywlc9N8QjdXNUZPSVVieFU/view)

**Comment by miztroh** [comment]
Confirmed.  Updated title to more accurately reflect the issue.

**Comment by miztroh** [comment]
@maxiplay You should be good to go.
