### ISSUE TITLE
Impossible to unbold after remove all

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#181]
New test with bolding 

[video](https://drive.google.com/file/d/0Bz9a1ywlc9N8dlhFTkFPWnhOV2s/view)

**Comment by miztroh** [comment]
In your test, you haven't actually removed all.  You're cursor is inside of the empty heading element.  Headings will always indicate bold.  If you press backspace once more, it will delete the heading element and the bold indicator will reset.

**Comment by maxiplay** [comment]
It is not a standard behavoir for an editor when you use CTLR+A. Even the bold option should be deleted

You can test with word, ckeditor or other known editor it is not the defautl behavior with CTRL+A

**Comment by miztroh** [comment]
[ckeditor's behavior seems to be the same.](https://drive.google.com/file/d/0B2fSCMPVNdMSRE1Nbjhhb3A3bkE/view)

**Comment by maxiplay** [comment]
Indeed but not on [word](https://drive.google.com/file/d/0Bz9a1ywlc9N8ZUhVcUhld2pEbVU/view)

Perhaps a web development constraint.

**Comment by miztroh** [comment]
Most of the basic editing is done with standard platform features (e.g. ``document.execCommand``, etc.).  So, if there's an issue, it might be with the platform or individual browser implementations.
