### ISSUE TITLE
Make selection part of the undo / redo history

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#183]
Hey,

I selected some text, CTRL+X to delete, CTRL+V to paste (bug or not for bolding ?)

And after I do CTLR+Z to cancel the paste.

The selector don't go to the good position.

https://drive.google.com/file/d/0Bz9a1ywlc9N8UGs1SFVVUnNnbTQ/view

**Comment by miztroh** [comment]
The bold is not a bug.  Again, it happens because the cursor is inside of a heading and then you're pasting content into it.

You are correct that ``wysiwyg-e`` does not currently restore selection when the undo / redo state changes.  I will add this as an enhancement.

**Comment by miztroh** [comment]
@maxiplay Take a look at the master build.  Selection is now included as part of the undo / redo history, so this should take care of the issue.

**Comment by maxiplay** [comment]
Can I test on webcomponents.org ?

**Comment by miztroh** [comment]
Yep, the fix was included in release v2.0.3.
