### ISSUE TITLE
Cursor jumping around in Chromium

### ISSUE THREAD

**Issue by DerNamenlose** [miztroh/wysiwyg-e#185]
Hi,

I've noticed a strange effect when using the editor demo in Chromium (Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)): loading the editor for the first time and starting to type makes the cursor jump back to the beginning of the line after the first character. If you type "This" on the keyboard, it comes out as "hisT" in the end, because you basically continue typing in front of the T after the jump. The effect goes away after deleting the line and starting again.

Additionally, when pressing Enter to get into a new line and then changing the style (e.g. to continue typing that line in bold), the cursor jumps back to the beginning of the line before. I cannot see any change inside the editor (e.g. DOM nodes disappearing). Only the cursor seems to move.

**Comment by miztroh** [comment]
I cannot reproduce this issue using the Chromium build you specified on Ubuntu Gnome and the official demo.

https://webcomponents.org/element/miztroh/wysiwyg-e

**Comment by DerNamenlose** [comment]
It only happens on the very first input after page load. Looking at the DOM, I see a difference: when loading the page, the editable-div is empty. After typing something and deleting all of it, the <div> still contains  <p><br/></p>, "fixing" the bug.

I tested a bit further by modifying the component and having the div always contain a single space (basically I just inserted a space in the <div> in line 423). This makes the bug go away. I'd investigate further, if you could point me where to look. Where do the <p> and the <br/> come from?
