### ISSUE TITLE
Fix backspace functionality when operating on target's immediate child text nodes

### ISSUE THREAD

**Issue by lastmjs** [miztroh/wysiwyg-e#187]
This thing is so awesome!!! But, I can't get the backspace to work...here is what I have basically:

```
<link rel="import" href="../../bower_components/wysiwyg-e/wysiwyg-e.html">

<wysiwyg-e id="textEditor" style="width: 500px; height: 250px; box-shadow: 0px 0px 3px grey" value="[[question.text]]" on-value-changed="textEditorChanged"></wysiwyg-e>
```

**Comment by lastmjs** [comment]
Looks like the problem is in here:

```
var singleBackspace = function () {
					if (this.target.children.length > 1) {
						document.execCommand('delete');
					} else if (this.target.children.length === 1) {
						if (this.target.children[0].textContent.length) {
							document.execCommand('delete');
						} else {
							document.execCommand('formatBlock', null, 'P');
						}
					}
				}.bind(this);
```

When I log it, `this.target.children` is an empty array.

**Comment by lastmjs** [comment]
Whoa, it's definitely not just me either. The demo doesn't let you backspace: https://www.webcomponents.org/element/miztroh/wysiwyg-e

I am on Chrome 59 on Linux

**Comment by lastmjs** [comment]
If I fiddle around a bunch and start typing and backspacing randomly, I can actually get the backspace to eventually start working.

**Comment by miztroh** [comment]
I cannot duplicate this on Ubuntu 17.04 / Chrome 59.

**Comment by lastmjs** [comment]
If I go to https://www.webcomponents.org/element/miztroh/wysiwyg-e, and type `hello` into the inline demo, and then if I hit backspace, it doesn't work.

**Comment by miztroh** [comment]
If you can give more details, I'll take another look.  As of now, I just can't replicate this.  See the attached screencast.

https://drive.google.com/file/d/0B2fSCMPVNdMSZ1dWUTNkZTdrNGM/view

**Comment by lastmjs** [comment]
Sorry, I think I mispoke. Can you try the editor that is [here](https://www.webcomponents.org/element/miztroh/wysiwyg-e) under the Usage title? That is where I can get it to break.

**Comment by lastmjs** [comment]
The demo you tried works for me as well, but no the demo under Usage.

**Comment by miztroh** [comment]
Looks like that one is broken by the constraints of the webcomponents.org site.  Can't really do anything about that.

**Comment by lastmjs** [comment]
This is from what we're building: https://prendus.com/question/cj51ccczl38hn0121ocavcv4x/demo

Once that loads, if I put the cursor at the end of hello and hit backspace, it doesn't work.

**Comment by miztroh** [comment]
OK, that's very helpful.  It looks like this may be a bug with having bare text as a value.  Try setting the initial value to ``<p>hello</p>`` instead of ``hello``.

**Comment by lastmjs** [comment]
That worked! So the editor isn't putting `<p>` tags around the first line I suppose

**Comment by miztroh** [comment]
Yeah, I need to add something to the sanitize method to wrap bare text inside p tags.  I've updated the title and tagged this as a bug.  Thanks for the information.

**Comment by lastmjs** [comment]
I could really use this soon, and I'm willing to do it if you'd like. If you could maybe point me in the right direction, just let me know

**Comment by lastmjs** [comment]
If it isn't too big of a change, it might be better for you to do it

**Comment by miztroh** [comment]
I fixed the backspace functionality to work with bare text nodes.  Please download a copy of the master branch and see if this meets your needs.

**Comment by lastmjs** [comment]
Works! Thanks a bunch!
