### ISSUE TITLE
Insert text at specific position

### ISSUE THREAD

**Issue by lastmjs** [miztroh/wysiwyg-e#194]
How would I go about this? How do I know what position the cursor is at?

**Comment by lastmjs** [comment]
I think I'm figuring it out using range0. I'm running into a little issue that would be nice to have solved in the editor. It looks like the range0.endOffset is the index of the cursor relative to the text that the user sees, without regard to any html tags present but not visible to the user. editor.text returns all of the html tags that the user does not see, and so the index is not accurate. It will be slightly complicated for me to figure out how to account for all of those tags. A better solution might be for the editor to account for those tags when calculating the index.

**Comment by lastmjs** [comment]
Actually, I think I was using value...my text property doesn't seem to be updating properly, it is always undefined

**Comment by lastmjs** [comment]
I'm using the range API to do this for now, not sure if that's the prescibed way, but I've got it working.

**Comment by miztroh** [comment]
``wysiwyg-e`` uses platform APIs wherever possible, so using the Range API would definitely be the way to go.

**Comment by lastmjs** [comment]
Just for future reference in case anyone comes across this, using `document.execCommand` seems like the way to go. For example, to insert text into the editor at the cursor:

```
        const textEditor = this.shadowRoot.querySelector('#textEditor');
        const selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(textEditor.range0);
        const theString = `Some text to insert`;
        document.execCommand('insertText', false, theString);
```
