### ISSUE TITLE
Clicking on a tool icon moves the cursor

### ISSUE THREAD

**Issue by lastmjs** [miztroh/wysiwyg-e#196]
Whenever I click on a tool icon, the cursor jumps to the end of the first line.

Example text:
```
Hello there


```

The first line says `Hello there`. I then hit enter twice and place the cursor at the beginning of the third line. When I click one of the tools, the cursor will jump back to the end of the first line. I believe this is the cause of issues I'm having with range0 not being set correctly when I am on empty lines.

**Comment by lastmjs** [comment]
I'm getting some other erratic behavior besides the case I described above. If the first line is empty, and lines below it have content, and then I click on a tool, the cursor jumps to the beginning of the line below it.

**Comment by lastmjs** [comment]
If I get some input on this, I can try my hand at fixing this.

**Comment by miztroh** [comment]
Issue confirmed and is caused in the following section of code.  I'll take a look at resolve this as soon as I can.

https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L1271-L1280

**Comment by miztroh** [comment]
@lastmjs Check out the above commit to the master branch and let me know if it resolves this issue for you.

**Comment by lastmjs** [comment]
Great, I really appreciate it. I'll get to all of these when I can, I've been occupied with some other tasks

**Comment by miztroh** [comment]
@lastmjs I went ahead and created a new release including several recent bug fixes.  You can just grab the latest release instead of the master branch.

https://github.com/miztroh/wysiwyg-e/releases/tag/v2.0.6

**Comment by lastmjs** [comment]
The issue seems to be resolved, thanks!
