### ISSUE TITLE
Erratic cursor behavior when inserting node through range0

### ISSUE THREAD

**Issue by lastmjs** [miztroh/wysiwyg-e#199]
If I insert an `img` or `p` or any other node that I've tried with `editor.range0.insertNode`, the cursor does not behave properly. It skips back and generally seems broken. I'm not sure if there is something with the Range API that I need to do to recalculate everything or what.

**Comment by lastmjs** [comment]
If I click into other inputs outside of the editor after inserting something with `editor.range0.insertNode`, the cursor keeps jumping into the editor. After I type around a bit in the editor and click into some other inputs outside of the editor for a bit, the erratic behavior seems to go away and everything works normally.

**Comment by lastmjs** [comment]
If I get some input on this, I can try my hand at fixing this.

**Comment by miztroh** [comment]
I can't seem to replicate this issue.  If you'd like to provide a step-by-step replication, I'll take another look.  I'm not sure what I can do about this if there is an issue as it's just the Range API.

**Comment by miztroh** [comment]
@lastmjs Can you confirm that this commit to the master branch resolves your issue?

**Comment by lastmjs** [comment]
v2.0.6 does not resolve this issue

**Comment by miztroh** [comment]
Ok, please provide a jsbin or other demo of this issue as I have not been able to reproduce it.
