### ISSUE TITLE
Default image tool, can't type

### ISSUE THREAD

**Issue by lastmjs** [miztroh/wysiwyg-e#200]
It looks like the default image tool's URL input is not stopping the propagation of the click event, so whenever I try to click the cursor jumps to the editor. This is happening on the latest version of Chrome in the demo on webcomponents.org

**Comment by miztroh** [comment]
@lastmjs Can you confirm that this commit to the master branch resolves your issue?

**Comment by lastmjs** [comment]
This is working in v2.0.6 on my machine! It is not working in the demo on webcomponents.org
