### ISSUE TITLE
[bug] many issues like link and picture not work!

### ISSUE THREAD

**Issue by AliMd** [miztroh/wysiwyg-e#204]
I cant insert link and picture even in your [demo](https://www.webcomponents.org/element/miztroh/wysiwyg-e/demo/demo/index.html)!

Thank you for making this project open source but ...
Please don't release v1 until fix all bugs and all feature works fine!
We report many bugs from our customers and testers
Unfortunately, I use this project in production mode!
Could you please fix these bugs as soon as possible?

**Comment by AliMd** [comment]
@miztroh 
I review your codes, and I think you need to rethink your code style and click strategy!
Could you please why you don't use `on-tap` with a separate function for each event like other components?

**Comment by AliMd** [comment]
@miztroh 
for use `contains` in shadow-dom you need to use `root` like `remove.root.contains(clickTarget)`
You fixed this in `image.html` but other file like `link.html` remain!
I think you must review and fix everything before publishing new release! 😞

**Comment by miztroh** [comment]
I had already fixed most of these issues in preparation for the (Polymer) 3.0 release.  I've backported the changes and created release 2.1.0.

**Comment by AliMd** [comment]
@miztroh 
Your demo still not work for me!
Undfortanaly we force to rewrite a new editor from zero
Thank you

**Comment by miztroh** [comment]
I don't know why the demo on webcomponents.org isn't working, but if you actually install this via bower, etc. it works just fine.
