### ISSUE TITLE
Table Tool: Brazilian Portuguese Translations

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#206]
Please translate the following:

```
'br': {
	'Cell After': 'Cell After',
	'Cell Before': 'Cell Before',
	'Column': 'Column',
	'Column After': 'Column After',
	'Column Before': 'Column Before',
	'Columns': 'Columns',
	'Delete': 'Delete',
	'Insert': 'Insert',
	'Row': 'Row',
	'Row After': 'Row After',
	'Row Before': 'Row Before',
	'Rows': 'Rows',
	'Show Footer': 'Show Footer',
	'Show Header': 'Show Header',
	'Table': 'Table'
}
```

**Comment by miztroh** [comment]
@Daniel-Gherard, can you take a look at this?

**Comment by Daniel-Gherard** [comment]
Sure... the translations are:

'br': {
	'Columns': 'Colunas',
	'Rows': 'Linhas',
	'Show Footer': 'Mostrar Rodapé',
	'Show Header': 'Mostrar Cabeçalho',
	'Table': 'Tabela'
}

**Comment by miztroh** [comment]
@Daniel-Gherard, thanks for the quick reply.  There ended up being more strings to translate.  Can you update your response to include all the strings now show above?  Thanks again!

**Comment by Daniel-Gherard** [comment]
@miztroh sure! I just updated the comment. Check it out.

**Comment by miztroh** [comment]
Awesome, thank you.  I always run the strings through Google Translate for my own education.  I have a question about all the before / after translations.

For example, when I translate "Célula Anterior" it gives me "Previous Cell".  The meaning I'm trying to achieve when you click ``Insert...`` -> ``Cell Before`` is:

[Insert a new] Cell Before [the currently selected cell].

Being completely uneducated in Portuguese, I wanted to ask if your translations are consistent with what I'm trying to say.   Thank you!

**Comment by Daniel-Gherard** [comment]
I see. I thought you meant something like: Go to the cell before or after.

In this case, the right translation should be: "Célula Antes" and "Célula Após".  To summarize:

'Cell After': 'Célula Após',
'Cell Before': 'Célula Antes',
'Column After': 'Coluna Após',
'Column Before': 'Coluna Antes',
'Row After': 'Linha Após',
'Row Before': 'Linha Antes',

English has this thing where the same word represent many different things. Portuguese, on the other hand, uses many words to represent different things. Hence the problem with the consistence.

**Comment by miztroh** [comment]
Gotch.  Thanks for the update.  It appears to be much more in keeping with my intended meaning.
