### ISSUE TITLE
getSelection() in safari is broken

### ISSUE THREAD

**Issue by Icer2000** [miztroh/wysiwyg-e#208]
If you use the wysiwyg editor in a Polymer 2 App inside of Shadowdom, the Toolbar Buttons  never get enabled.

The Problem seems to be, that getSelection is undefined in Safari 11.03.

**Comment by miztroh** [comment]
Yeah, there's a Safari bug filed for this.  There's not really anything I can do to work around this.  It's a critical feature of Shadow DOM and Safari doesn't support it yet.

https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/getSelection
https://bugs.webkit.org/show_bug.cgi?id=163921
