### ISSUE TITLE
_computeShowPlaceholder should return a value

### ISSUE THREAD

**Issue by feuerste** [miztroh/wysiwyg-e#209]
_computeShowPlaceholder currently doesn't return a value, see https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L1402
Please add a
`return showPlaceholder;`
Thank you!

**Comment by miztroh** [comment]
Good catch.  I know that worked at some point.  I'd have to dig through the commits to find out when it broke.  Thanks!
