### ISSUE TITLE
Input prompt don't work in "standard" way

### ISSUE THREAD

**Issue by mstahv** [miztroh/wysiwyg-e#216]
Typically input prompt is gray and disappears when user focuses the field. With wysiwyg-e it stays there until one writes the first character.

<img width="276" alt="screen shot 2018-03-05 at 16 03 56" src="https://user-images.githubusercontent.com/1478052/36979021-dc1f5412-208e-11e8-87f0-724c8ed92ede.png">

**Comment by miztroh** [comment]
Please provide your operating system / browser version.  Thanks!

**Comment by mstahv** [comment]
Mac OS X latest, tested with Safari and Chrome.

**Comment by miztroh** [comment]
I've changed the styling from ``font-style: italic;`` to ``opacity: 0.5;``.  However, hiding the placeholder on focus is not the standard.  I can't say if that's the way Safari handles it, but Chrome and Firefox on Windows / Linux don't operate that way.  I will continue to show the placeholder until text is entered.   If you need to change this behavior, you can override the ``_computeShowPlaceholder`` method.
