### ISSUE TITLE
Change for a more appropriate heading icon

### ISSUE THREAD

**Issue by tahitibob035** [miztroh/wysiwyg-e#217]
Hello,

I created a custom font-size tool and i want to use the `editor:format-size` icon from https://github.com/PolymerElements/iron-icons/blob/master/editor-icons.html for the button which updates the font size.
Unfortunately, this icon is already use for the heading button. It exists the icon `editor:title` which can do the job for this heading feature.

Could you help me please ?

**Comment by miztroh** [comment]
Done.  Thanks for the suggestion!
