### ISSUE TITLE
Demo failed in https://www.webcomponents.org/element/miztroh/wysiwyg-e/demo/demo/index.html

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#218]

**Comment by jay8t6** [comment]
Its probably because of the version mismatch.. check https://github.com/miztroh/wysiwyg-e/issues/220

**Comment by miztroh** [comment]
@jay8t6 Good catch.  Resolved in https://github.com/miztroh/wysiwyg-e/releases/tag/v2.1.2.
