### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by rovervannispen** [miztroh/wysiwyg-e#219]
I'm getting the following error message when trying to install `wysiwyg-e#1.1.2`

bower selection-mgr#^1.0.0                  ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/miztroh/selection-mgr.git", exit code of #128 fatal: remote error:    Repository not found.

I can't update to the 2.0 element in my application yet.. 😢

**Comment by miztroh** [comment]
Unfortunately, I don't have a good support story for you here.  At the time 2.0 was released, the ``selection-mgr`` and ``undo-mgr`` functionalities were moved into ``wysiwyg-e`` itself.  Also at that time, GitHub did not support archiving repos to make them read-only.  So, those repositories were deleted.  I don't have copies of that code.  I know that's frustrating and I apologize.

You should really look at migrating to Polymer 2. It shouldn't take much effort to transition your 1.x elements to become hybrid-mode elements that work more or less like 1.x elements but that can coexist with 2.x elements on the same page.

https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements
