### ISSUE TITLE
Feature Request: Insert HTML into Editor and enable focus

### ISSUE THREAD

**Issue by jay8t6** [miztroh/wysiwyg-e#222]
The following addresses these two features:
- Insert html into editor
- enable editor focus

https://github.com/miztroh/wysiwyg-e/pull/221

**Comment by miztroh** [comment]
As mentioned in the PR, the 2.x branch is now under a feature freeze since the release of 3.x (master branch).  Feel free to update your code and submit a new PR.

**Comment by miztroh** [comment]
I'll close this until such a time as a new PR is submitted.
