### ISSUE TITLE
Component is broken after clearing entered text in FF 59 on macOS

### ISSUE THREAD

**Issue by pleku** [miztroh/wysiwyg-e#227]
Tested with component 2.1.3 version, macOS 10.13.4 (high sierra), FF Quantum 59.0.2 (64-bit)

### Steps to reproduce:
1. Enter some text to component
2. Remove all entered text (with backspace or select-all + remove)
3. enter text

**Expected**: text is entered normally
**Outcome**: every entered character goes as the first character and adds a whitespace before the previously entered character 
<img width="620" alt="screen shot 2018-05-16 at 11 49 03" src="https://user-images.githubusercontent.com/1478381/40106742-3362c5c6-58ff-11e8-8b04-5978d1811650.png">

There is no errors on the browser console.

**Comment by miztroh** [comment]
I have also backported the fixes from the 3.x (master) branch to the 2.x branch and created a new 2.x release.

https://github.com/miztroh/wysiwyg-e/releases/tag/v2.1.4

**Comment by pleku** [comment]
I can confirm it works now! Awesome, thanks for the backporting!
