### ISSUE TITLE
Migrating the elements to @material components instead of @polymer

### ISSUE THREAD

**Issue by phani1kumar** [miztroh/wysiwyg-e#228]
Hi @miztroh 

Thank you very much for such a wonderful tool. Do you have plans to use @material components instead of the @polymer components?

@polymer components, though on the surface are using Polymer 3.0, are actually legacy stuff internally and carry lot of baggage along with them. [@material](https://github.com/material-components/material-components-web-components) components on the other hand are light weight and are derived from lit-html. 

Do you have any plans to migrate to the lit-html variation of Polymer?
I am using this component as part of my CMS(Content Management System) screens, I am not that much worried about performance as of now, but would be nice to see the CMS screens of my application are as fast as my regular application. 

If I find time, I'll try to make the changes myself (if I do, I'll submit a pull request). But just wanted to check if you have any plans on these lines.

Regards,
Phani

**Comment by miztroh** [comment]
Hello @phani1kumar!  Glad you're enjoying this tool.  I think we're making something great here.  I already have a branch in the works that is rewritten based on ``lit-element`` (``lit-html``) and uses the Material Web Components.  Neither of these has a 1.0 release yet, so I can't say for sure when this will be ready.  Feel free to check it out.

https://github.com/miztroh/wysiwyg-e/tree/lit-element-rewrite
