### ISSUE TITLE
Add view only tool

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#28]
Possibly use `marked-element ` to do this.  This would be a read only view where you could just click on links, etc.

```html
<wysiwyg-e id="wEditor" value='<p><a href="https://github.com/miztroh/wysiwyg-editor">Hello</a>, World!</p>' style="height: 100vh;">
...
<wysiwyg-e>

<marked-element id="viewContent">
     <div class="markdown-html code"></div>
</marked-element>
```

```javascript
setViewContent: function() {
   this.$.viewContent.markdown = this.$.wEditor.value;
},
```

**Comment by miztroh** [comment]
@chuckh Can you confirm this what you are looking for?

**Comment by chuckh** [comment]
@miztroh That is great, thanks so much!  :100: 

I appreciate all your hard work on this. Let me know if I can help in any capacity.

**Comment by miztroh** [comment]
@chuckh No problem.  I'm so focused on adding / polishing features on the road to a 1.0 release, I haven't had much time to flesh out the unit tests.  If you've have / want some experience with ``web-component-tester``, I'd love to see more tests added.

Tests covering selection should be added to https://github.com/miztroh/selection-mgr.
Tests covering undo / redo history management should be added to

**Comment by chuckh** [comment]
I will give it a try adding some more tests later today.
