### ISSUE TITLE
Styling (built-in, end-user, etc.)

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#36]
wysiwyg-e needs to provide some default styling of editable content.  Additionally, it needs to provide some custom CSS properties / mixins to allow end users to override toolbar and editable content styles.

For editable content, my current thinking is to provide lots of custom CSS mixins to cover standard element types:

```
#editable h1 {
  @apply(--wysiwyg-content-h1);
}

#editable p {
  @apply(--wysiwyg-content-p);
}

#editable blockquote {
  @apply(--wysiwyg-content-blockquote);
}
```

**Comment by miztroh** [comment]
@chuckh Thoughts?

**Comment by miztroh** [comment]
@chuckh I've added some default styles to a few element types within the editable area.  I've also added mixins like those mentioned above to all the relevant elements I could think of.  Take a look at let me know if this meets your needs.

As more tools are added to the mix (e.g. ``audio`` and ``video``), I'll have to add more mixins.

**Comment by chuckh** [comment]
@miztroh Great job!  You are fast, I was just try to comment and you already made the changes. Thanks.

A few suggestions. For toolbar could you expose the following (I know you have done `--wysiwyg-toolbar` already).

### Styling for Toolbar
The following custom properties and mixins are available for styling:

Custom property | Description | Default
----------------|-------------|----------
`--wysiwyg-toolbar-background-color`   | Toolbar background color                                            | `--primary-background-color`
`--wysiwyg-toolbar-color`              | Toolbar foreground color                                            | `--dark-theme-text-color`
`--wysiwyg-toolbar-max-height`         | Custom max-height for toolbar                                       | `288px`
`--wysiwyg-toolbar`                    | Mixin applied to the wysiwyg-e toolbar                              | `{}`

**Comment by miztroh** [comment]
@chuckh I don't see "max-height" in the ``paper-toolbar`` documentation.  I've had to set height to auto because the number of tools in use can vary.  It seems like providing a max-height option would be problematic.  However, I am considering making the toolbar vertical in narrow layouts.  Right now, it's difficult to use the editor from a phone because of how much space the toolbar takes up.  I'll probably create another issue for that.

**Comment by chuckh** [comment]
@miztroh you are correct I don't see it either. In addition to doing vertical toolbar you might consider taking H1-H2 and putting in a drop down menu like Github does.

![image](https://cloud.githubusercontent.com/assets/19915/12983437/20f19778-d09e-11e5-8969-2edf40265b72.png)

**Comment by chuckh** [comment]
Might consider importing defaut-theme.html (https://github.com/PolymerElements/paper-styles/blob/master/default-theme.html):

```
<link rel="import" href="../paper-styles/default-theme.html">
```

See example at: https://github.com/PolymerElements/paper-listbox/blob/master/paper-listbox.html#L13

**Comment by miztroh** [comment]
``wysiwyg-toolbar-background`` property, ``wysiwyg-toolbar-color`` property, and ``wysiwyg-toolbar`` mixin added.  I think I'm going to pass on importing the default theme.  I'm a little more opinionated on the default ``wysiwyg-e`` styles.

I believe these changes address the main concerns of this issue.  I'm going to close this one.  I'll open another to track combining the headings into a dropdown.

@chuckh Thanks for the input.

**Comment by chuckh** [comment]
:+1:
