### ISSUE TITLE
Make toolbar vertical, left-align on narrow screen devices (e.g. mobile)

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#40]

**Comment by chuckh** [comment]
@miztroh in addition to doing vertical toolbar you might consider taking H1-H2 and putting in a drop down menu like Github does.

![image](https://cloud.githubusercontent.com/assets/19915/12983437/20f19778-d09e-11e5-8969-2edf40265b72.png)

**Comment by miztroh** [comment]
Reopening because tooltip positions aren't correct in narrow mode.
