### ISSUE TITLE
Add tools tooltip descriptions

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#42]
Like bold below:
![image](https://cloud.githubusercontent.com/assets/19915/12984958/25bb4ff4-d0a5-11e5-95fb-e1367904a63e.png)

### Need Tooltip description as well as shortcut key
- [ ] View Menu
- [ ] Strikethrough
- [ ] Remove formating
- [ ] Link
- [ ] Image
- [ ] Number list
- [ ] Bullet list
- [ ] Indent right
- [ ] Indent left
- [ ] H1-H6
- [ ] Undo
- [ ] Redo

**Comment by miztroh** [comment]
Also fixed keyboard shortcut for Blockquote (Ctrl / Cmd + Q) and changed List keyboard short from Ctrl / Cmd + Shift + L to just Ctrl / Cmd + L.

**Comment by chuckh** [comment]
Looks good.  Need to change Blockquote shortcut Cmd + Q.  This will cause Mac browser to close.  Maybe Ctrl / Cmd O or E. 

Cmd T creates new Tab.

**Comment by miztroh** [comment]
While the editable region has focus, it should trap Cmd + Q.  However, I'd hate for anyone to press it while they think it has focus and close their browser by accident.  Maybe I can just do Ctrl + '.

**Comment by chuckh** [comment]
I was one of those people when testing `Cmd Q` it close Chrome and Firebox even when region had focus it.

`Ctrl + '` sounds good

**Comment by chuckh** [comment]
While working on the doc I created the below shortcuts list.  Found couple if issues:

- Ordered list and Bullet list tooltip shows Cmd / Ctrl L and just tip of List
- Remove Format does not seem to work
- Need to add normal format to H1-H2 pull down
- Adding new line by pressing enter at end of existing line cursor jumps to top or you loose it.

### Shortcut List

Command         | Shortcut Mac | Shortcut Windows
----------------|--------------|-----------------
`Bold`          | Cmd + B      | Ctrl + B
`Italc`         | Cmd + I      | Ctrl + I
`Underline`     | Cmd + U      | Ctrl + U
`Strikethrough` | Cmd + S      | Ctrl + S
`Remove Format` | Cmd + Space  | Ctrl + Space
`Link`          | Cmd + L      | Ctrl + L
`Image`         | Cmd + M      | Ctrl + M
`Ordered List`  | Cmd + L      | Ctrl + L (should this be something different maybe letter O)
`Bullet List`   | Cmd + L      | Ctrl + L  
`Indent`        | Tab          | Tab
`Outdent`       | Shift + Tab  | Shift + Tab
`Headings`      | Cmd + #      | Ctrl + #
`H1`            | Cmd + 1      | Ctrl + 1
`H2`            | Cmd + 2      | Ctrl + 2
`H3`            | Cmd + 3      | Ctrl + 2
`H4`            | Cmd + 4      | Ctrl + 3
`H5`            | Cmd + 5      | Ctrl + 3
`H6`            | Cmd + 6      | Ctrl + 6
`Normal`        | Cmd + 7      | Ctrl + 7 (consider adding)
`Quote`         | Cmd + '      | Ctrl + '
`Undo`          | Cmd + Z      | Ctrl + Z
`Redo`          | Cmd + Y      | Ctrl + Y
