### ISSUE TITLE
Can't escape from View and Header dropdowns

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#45]
When you select the View dropdown menu (gears icon) or the Header dropdown menu you can't exit without making a selection. The `escape key` or tapping the content area should exit the dropdown menu.

**Comment by miztroh** [comment]
I made a change to the ``selection-mgr`` dependency today.  Can you run a ``bower update`` and then test this again after clearing cache (or in an incognito window)?

**Comment by chuckh** [comment]
Tried it again in Chrome incognito mode it worked fine both locally after doing `bower update` and on https://miztroh.github.io/bower_components/wysiwyg-e/demo/.  Looks like it was a caching issue.

**Comment by miztroh** [comment]
Great, thanks.
