### ISSUE TITLE
Add Alignment Tool

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#48]
Add a dropdown menu to  center, left, right, or full justify. 

Can use theses document.execCommand commands:

```
justifyCenter
Centers the selection or insertion point.

justifyFull
Justifies the selection or insertion point.

justifyLeft
Justifies the selection or insertion point to the left.

justifyRight
Right-justifies the selection or the insertion point.
```

See https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by miztroh** [comment]
Yeah, I'd been thinking about this too.  I've been frequently that page while developing `wysiwyg-e` ;)

**Comment by chuckh** [comment]
@miztroh all the changes looks great :100: This editor coming together very nicely!
