### ISSUE TITLE
Clear Formatting removes code but leaves behind pre

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#49]
Testedhttp://miztroh.github.io/bower_components/wysiwyg-e/demo/ use the Chrome 48 on Mac in Incognito mode. Got the following results:

### Not Working

- [ ]  Removing Blockquote formatting, clicking on List icon again removes it
- [ ]  Removing H1-H6 formatting
- [ ]  Removing list item(s) formatting, clicking on List icon again removes it
- [ ]  Removing link formatting
- [ ]  Fully removing code formatting, (removes code but not pre)
- [ ]  Removing ident formatting 

### Working
- [x] Removing bold
- [x] Removing italic
- [x] Removing underline
- [x] Removing Strikethrough

Not sure if this is expected behavior, either we should fix or document.

**Comment by miztroh** [comment]
Quote from https://w3c.github.io/editing/execCommand.html:

> A removeFormat candidate is an editable HTML element with local name "abbr", "acronym", "b", "bdi", "bdo", "big", "blink", "cite", "code", "dfn", "em", "font", "i", "ins", "kbd", "mark", "nobr", "q", "s", "samp", "small", "span", "strike", "strong", "sub", "sup", "tt", "u", or "var".

So, most of this is not a problem.  However, removing `code` elements but leaving `pre` elements behind is definitely a problem.  I'll rename this issue to focus on that.

If you can think of a concise way to document the limitations of the clear tool, feel free to submit a PR.

**Comment by chuckh** [comment]
So then we have no way of remove formatting `H1-H6` other then deleting the line. Maybe we could add a Paragraph option to the H1-H2 dropdown menu?

**Comment by miztroh** [comment]
Yeah, adding "Paragraph" to the heading tool is definitely the way to go.  I'll add a separate issue.

**Comment by miztroh** [comment]
@chuckh Now, the "Clear Formatting" tool will move non-code nodes out of pre nodes and eliminate empty pre nodes.

**Comment by chuckh** [comment]
:+1:

**Comment by hyyan** [comment]
It seems the fix for this issue cause another issue , as you can see in the Gif , we can not edit the code and enter a new line without creating a new code block .

![ysiwyg-e20160719123532](https://cloud.githubusercontent.com/assets/4313420/16947162/bcfd3118-4dad-11e6-86c6-54480078d4bd.gif)

**Comment by hyyan** [comment]
@miztroh is there a chance to fix to this problem , I have mentioned this issue many times but with no response , I have sent a PR and it was not accepted , the Implementation of [sanitize method](https://github.com/miztroh/wysiwyg-e/blob/master/wysiwyg-e.html#L654) is not correct .

**Comment by miztroh** [comment]
@hyyan Please open this as a new issue as the issue described here as been resolved.
