### ISSUE TITLE
Which tools should be able to modify code blocks?

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#51]
It seems to me that code blocks should not be affected by bold, italic, underline, strikethrough, headings, etc.  This is not currently the case.  @chuckh Opinions?

**Comment by chuckh** [comment]
I agree except possibly bold. Sometimes it is nice to be able to bold some code to make it stand out.

**Comment by miztroh** [comment]
After giving this some thought, it seems to me that ``wysiwyg-e`` should not enforce a limitation here.  ``wysiwyg-e`` does not exist to serve as a code editor, but rather a general purpose WYSIWYG editor.  If people choose to format text inside of a code block for emphasis, ``wysiwyg-e`` will not prohibit them.
