### ISSUE TITLE
Rework heading tool to be a more general block formatting tool (paragraph, blockquote, etc.)

### ISSUE THREAD

**Issue by miztroh** [miztroh/wysiwyg-e#52]

**Comment by chuckh** [comment]
:+1:

**Comment by miztroh** [comment]
@chuckh After further view, I think I'm going to leave this as is.  I don't want to combine blockquote with this, because headings are allowable within blockquotes.  Additionally, there's already a way to switch from any heading to a paragraph without deleting the whole line.  The dropdown tracks which heading (if any) is currently in use.  Clicking the selected heading will convert the text to a paragraph.  This also works with the keyboard shortcuts.  For example, Ctrl + 1 will create an H1.  Pressing Ctrl + 1 again will swap the H1 out for a P.

**Comment by chuckh** [comment]
@miztroh I still think adding Paragraph will be more intuitive to the average user then clicking with H1-6 they previously selected.

**Comment by miztroh** [comment]
I agree.  Will add paragraph option and Ctrl (Cmd) + 0 shortcut.
