### ISSUE TITLE
Increase width of Link and Image Popup

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#53]
Increase width so you can see more of URL. 

## Maybe width 400px  (use for Desktop & Tablets)
![image](https://cloud.githubusercontent.com/assets/19915/13036336/8fc09b0e-d319-11e5-8846-33bd47966857.png)

## Current (Use for mobile)
![image](https://cloud.githubusercontent.com/assets/19915/13036323/2d61d40a-d319-11e5-8886-2bedb6115bca.png)

**Comment by miztroh** [comment]
@chuckh Good suggestion.  Done.

**Comment by chuckh** [comment]
@miztroh Nice work, it looks good. :100:
