### ISSUE TITLE
Enter key inserts a line before

### ISSUE THREAD

**Issue by hugozap** [miztroh/wysiwyg-e#54]
When testing (the online demo) sometimes, when pressing ENTER it inserts a line before and cursor jumps to position 0.
(edit: Tested on Chrome / Mac )

**Comment by hugozap** [comment]
One way to reproduce it is to position the cursor at the end of a H1 header and press enter

**Comment by miztroh** [comment]
I can't seem to duplicate this on Windows.  Before I fire up a VM to test this, maybe @chuckh can confirm.  Thanks for the report.

**Comment by chuckh** [comment]
I just tested on a Mac tried Chrome, Safari and Firefox got the same behavior on all of them.  I tested H1, H2, and H3 jumps to top after pressing Enter at end of line then If your start typing it puts content at top of document.  Did not display this behavior for P, blockquote, image, link, or lists.

**Comment by miztroh** [comment]
@hugozap @chuckh Can you confirm this fixes it for you?

**Comment by chuckh** [comment]
I just tested on a Mac tried Chrome, Safari and Firefox and it worked correctly! 💯
