### ISSUE TITLE
Removing iron-overlay behaviour from demo?

### ISSUE THREAD

**Issue by WaverleyDesign** [miztroh/wysiwyg-e#70]
I'm just trying out the demo in my own project and get figure out how to just use the editor without the iron-overlay messing up the rest of my app - I'd just like it to display inline. But when I just remove the iron-overlay behaviour, nothing displays?

**Comment by miztroh** [comment]
I take it you figured it out?  The demo page uses a separate element wrapper to make it appear in that overlay.

**Comment by WaverleyDesign** [comment]
Yeah, thanks for that and sorry for the bother!
