### ISSUE TITLE
Facilitate integration of grammar checking feature

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#73]
From parent element of wysiwyg-e I send an AJAX request to a grammar checkin server. My first simple approch is to change content of editor applying a span with an other color text around error: 
`<span style="color:red">error</span>` but the sanitize function replace the span by a `<p>` and remove the style attribute.  What do you preconize ? From now the only solution I see is to modify the sanitize function..

**Comment by miztroh** [comment]
Yeah, you can't modify the content itself for grammar / spelling checks.  For each modification, a new undo / redo history record is created.  We don't want users to be able to undo to a state where grammar errors are visible.  Any error indicators will have to live in a separate container (e.g. overlay).

**Comment by maxiplay** [comment]
Indeed I did not think to the undo/redo problem. And the overlay is not satisfying of my point of view for user experience. And I imagine the differents problems with positionning an overlay on word in a text node.. And like you said past, problems with scroll.. Need to meditate to an other solution.

**Comment by maxiplay** [comment]
After some search, I'll be forced to to use an oldSchool popup saying grammar error with text selection in the editor. I will add a button in bar button to open the dialog. Example https://www.spellchecker.net/spellcheck/
Perhaps a day the web platform will give a API to acces to spellCheck.

**Comment by miztroh** [comment]
If you write the tool plugin such that it selects the text that contains the grammar issue, you can then position a tooltip at the selected text using ``this.range0.getBoundingClientRect()`` inside any of your tool's methods.

**Comment by maxiplay** [comment]
Good idea. Thx

**Comment by maxiplay** [comment]
Hello,

I meet a problem with the `&nbsp;` character and perhaps others html special chars. In the editor, when I copy and paste a text with no-break space, the text nodes again contains the html special char `&nbsp;`.(open dev tool and inspect)

When I send the full innerHTML to my grammar checker, before checking, I can separate markup from text to specify them to the checker. Thanks to that I can check grammar error with exact position in innerHTML and apply position to the overlay with range selector.

The problem is the grammar checker doesn't understand the word `&nbsp;`.

When I test the grammar checker in their [example](https://languagetool.org/), they use TinyMCE editor. With this editor, when I paste the same text, it seems that `&nbsp;` is transformed into a simple space character. It provoke a grammar error (I tested in french, the character ';' need a fine non-breaking space before it). After that, the example editor propose to add this fine non-breaking space. You click to add. Now inspect the text node. The next node does not contain `&nbsp;` but a simple character fine non-breaking space (unicode ?)

You can try with this sentence with french language

`en l’honneur de Bilbon&nbsp;;`in this [site](https://languagetool.org/)

**Comment by maxiplay** [comment]
Hi. In order to manage `&nbsp;` i coded the fact to don't take in account `&nbsp;` in grammar checking server side and recalculate the errors positions after checking. After this, I had to create a recursive javascript algorithm to know what HTML node to use for range selector. Because my checking server give me a start and a end position relative to the innerHTML. After this I applied differents calculs to recalculate position in contenteditable with `&nbsp;` taked in account.

That was a successful in firefox and chrome but when I tested in IE11 my recursive algorithm failed because IE11 manage textNode differently (in IE11 a textNode can be splitted in multiples other text node if the text node have typical characters(example :  - or _ or 'etc.). So I adapted my algorithm to fit with specifics IE.

Conclusion ; It's not that simple.

**Comment by jperera84** [comment]
Hello @maxiplay , I know this is nothing related with the grammar theme but I really need help on this and I was wonder if you could give me an idea.
I'm very sure that the problem that I have is something that I don't know but I would like ask you for help, I installed the element via bower in my polymer project, all the installation went fine I don't got any error.
After that I reference the component in the element.html:
`<link rel="import" href="../bower_components/wysiwyg-e/wysiwyg-e.html">`
And after that I put the usage code in this page to test the component, when I refresh my website I got the following error in the console:

> polymer-mini.html:2061 Uncaught TypeError: tools[i]._setRange0 is not a function

Please could you help me to find a solution for this?
Thanks in advance

**Comment by miztroh** [comment]
I will address the ``&nbsp;`` issue in the sanitizer function.  Opening this as a separate issue.

**Comment by maxiplay** [comment]
I'm curious about how your editor works. I first tried to sanitize in sanitize function but the focus was lost and ctrl z had errors. Could you provide a technical explanation of the worflow ?

**Comment by miztroh** [comment]
The sanitize function is an override of the function from the ``undo-mgr`` behavior.

See https://github.com/miztroh/undo-mgr/blob/master/behavior.html#L67-L76.

I'm going to close this issue.  Please open a new issue for any further specific bugs / enhancements.
