### ISSUE TITLE
I got error in the element code

### ISSUE THREAD

**Issue by jperera84** [miztroh/wysiwyg-e#76]
Hello,
I'm very sure that the problem that I have is something that I don't know but I would like ask you for help, I installed the element via bower in my polymer project, all the installation went fine I don't got any error.
After that I reference the component in the element.html:
`<link rel="import" href="../bower_components/wysiwyg-e/wysiwyg-e.html">`
And after that I put the usage code in this page to test the component, when I refresh my website I got the following error in the console:

> polymer-mini.html:2061 Uncaught TypeError: tools[i]._setRange0 is not a function

Please could you help me to find a solution for this?
Thanks in advance

**Comment by miztroh** [comment]
My guess is that you're not importing all the tools (bold, underline, etc.) that your HTML is using.  Check the demo for an example of what you should be including.

**Comment by jperera84** [comment]
Thank you very much I will check this and I let you know, thank you very much I really appreciate your help, by the way the control is great.

**Comment by maxiplay** [comment]
If you want more help, post a plunkr with your code example that don't work and I will check it.

Example of plunkr with polymer https://plnkr.co/edit/KqR3X5PKfuTKq7oNgTvO?p=info

**Comment by miztroh** [comment]
Closing.
