### ISSUE TITLE
Responsive behavior failed if window stay large

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#79]
If I set a small size to the container, the responsive behavior does not change (button verticals). If I change the windows size it's work. Do you use media queries to apply responsiveness ?

Could you not use https://github.com/PolymerElements/iron-resizable-behavior in order to apply responsiveness following the real size of the container ?

First capture is with manual small size , Second with window size.

![capture](https://cloud.githubusercontent.com/assets/8363127/15270788/473afa96-1a2c-11e6-880b-5b563df06c93.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8363127/15270790/4b8d61c4-1a2c-11e6-891c-19159dc3c285.PNG)

**Comment by miztroh** [comment]
I will look at adding a ``forceNarrow`` property that you can use for this purpose.

**Comment by miztroh** [comment]
@maxiplay Your screenshots have me intrigued.  Is there somewhere online I can see your project?

**Comment by maxiplay** [comment]
I could give you a test login very soon. For now my test environnement is not presentable ;)

**Comment by miztroh** [comment]
@maxiplay Looking forward to it.
