### ISSUE TITLE
Issue with the Image tool

### ISSUE THREAD

**Issue by jperera84** [miztroh/wysiwyg-e#82]
II have this problem when I tried to enter an Image URL in the Image tool there is some problems:

1. I can't use the KeyBoard to move to the start or end of the url.
2. I can't click on the Url textbox because url disappear.
3. When I enter the url if I click on the Ok button to show the image in the content nothing happen, the url is remove and nothing happen, I mean is like no event were trigger when I click the button.

Everything else seems to be working fine but I just wonder if it is something that I missed or some. Thank you I really appreciate your help

**Comment by jperera84** [comment]
Please, any help on this, I can't find the problem. In the Browser Console I don't have any error, also I checked the network tap in the Browser and I don't have any problem all the files are downloaded.
Thanks in advanced
## Files References
```
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/paper-styles/typography.html">
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">
<link rel="import" href="../bower_components/iron-localstorage/iron-localstorage.html">
<link rel="import" href="../bower_components/iron-overlay-behavior/iron-overlay-behavior.html">
<link rel="import" href="../bower_components/font-roboto/roboto.html">
<link rel="import" href="../bower_components/marked-element/marked-import.html">
<link rel="import" href="../bower_components/wysiwyg-e/wysiwyg-e.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/bold.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/italic.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/underline.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/strike.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/clear.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/link.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/image.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/ordered.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/unordered.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/indent.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/outdent.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/heading.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/justify.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/blockquote.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/undo.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/redo.html">
```

**Comment by miztroh** [comment]
@jperera84 Please provide a an example of your issue.  If you can't get a JS Bin working, I'll accept an animated GIF recording that demonstrates your problem.

**Comment by jperera84** [comment]
@miztroh This is a gif that show the issue:
![issue](https://cloud.githubusercontent.com/assets/13193138/17122790/7aff5058-52ac-11e6-9386-88924d425d61.gif)
In the previous post I copy/paste the references.
As you could see in the gif, there is something weird with the image element, I can copy or write the url but I can't move the cursor the keyboard, and also if I click in any place the url is erased and when I click in the OK button the url is removed and nothing happen.
Please I really appreciate any help on this. Thanks

**Comment by miztroh** [comment]
I've made a change to the image tool.  See https://github.com/miztroh/wysiwyg-e/issues/91.

Please do your test again, but use the demo page instead of your own. Make a new .gif using the demo page.

https://miztroh.github.io/bower_components/wysiwyg-e/

**Comment by jperera84** [comment]
@miztroh, I tested the demo with the new version for the image tool, and it really works fine here is the gif:
![issue-demo](https://cloud.githubusercontent.com/assets/13193138/17143410/2a217ec0-5321-11e6-883b-c1066ec1549c.gif)
After that I updated my project and it seems to be updated but it doesn't work fine:
![issue-pro](https://cloud.githubusercontent.com/assets/13193138/17143539/941be1bc-5321-11e6-9506-db558a2d84ea.gif)
I know is something on my project, this is all the references that I have in my project:
`<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/paper-styles/typography.html">
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">
<link rel="import" href="../bower_components/iron-localstorage/iron-localstorage.html">
<link rel="import" href="../bower_components/iron-overlay-behavior/iron-overlay-behavior.html">
<link rel="import" href="../bower_components/paper-material/paper-material.html">
<link rel="import" href="../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../bower_components/iron-icons/editor-icons.html">
<link rel="import" href="../bower_components/iron-icons/maps-icons.html">
<link rel="import" href="../bower_components/iron-icons/social-icons.html">
<link rel="import" href="../bower_components/iron-icon/iron-icon.html">
<link rel="import" href="../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="../bower_components/paper-input/paper-input.html">
<link rel="import" href="../bower_components/paper-spinner/paper-spinner.html">
<link rel="import" href="../bower_components/paper-toast/paper-toast.html">
<link rel="import" href="../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../bower_components/paper-ripple/paper-ripple.html">
<link rel="import" href="../bower_components/paper-input/paper-textarea.html">
<link rel="import" href="../bower_components/paper-button/paper-button.html">
<link rel="import" href="../bower_components/iron-image/iron-image.html">
<link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
<link rel="import" href="../bower_components/paper-toggle-button/paper-toggle-button.html">
<link rel="import" href="../bower_components/moment-element/moment-import.html">
<link rel="import" href="../bower_components/font-roboto/roboto.html">
<link rel="import" href="../bower_components/marked-element/marked-import.html">
<link rel="import" href="../bower_components/wysiwyg-e/wysiwyg-e.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/bold.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/italic.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/underline.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/strike.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/clear.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/link.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/image.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/ordered.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/unordered.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/indent.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/outdent.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/heading.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/justify.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/blockquote.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/undo.html">
<link rel="import" href="../bower_components/wysiwyg-e/tools/redo.html">`

And this is my complete code for the element:
`<dom-module id="my-blogentry">
  <template>
    <style include="iron-flex iron-flex-alignment iron-flex-factors iron-positioning"></style>
    <style>
      :host {
        display: block;
      }
      .div-general{
        margin: 24px;
        border-radius: 5px;
        color: #fff;
        height: auto;
        min-height: 400px;
        @apply(--layout-horizontal);
				@apply(--layout-wrap);
        @apply(--layout-around-justified);
      }
      .div-right{
        @apply(--layout-vertical);
        height: auto;
        min-height: 400px;
        min-width: 300px;
        width: 500px;
        margin: 8px;
      }
      .div-left{
        @apply(--layout-vertical);
        height: auto;
        min-height: 400px;
        width: 700px;
        min-width: 300px;
        margin: 8px;
      }
      .div-header{
	    	height: 60px;
	    	width: 100%;
		  }
      .div-list-content{
        padding: 16px;
        height: 400px;
        overflow: scroll;
        background-color: #212121;
      }
      .card {
        box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2);
        padding: 0px;
        margin-top: 16px;
        background-color: #fff;
        color: #757575;
        min-height: 120px;
        height: auto;
        @apply(--layout-horizontal);
        position: relative;
        cursor: pointer;
      }
      .div-left-side{
        min-width: 80px;
        width: auto;
        background: var(--dark-primary-color);
        display: table-cell;
        text-align: center;
        vertical-align: middle;
        padding-top: 36px;
        padding-bottom: 36px;
      }
      .div-text-side{
        max-width: 300px;
        width: 100%;
        padding: 36px;
        @apply(--layout-vertical);
      }
      .div-right-side{
        min-width: 80px;
        width: auto;
        float: left;
        padding-top: 36px;
        padding-bottom: 36px;
      }
      .card-content {
        box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2);
        padding: 16px;
        background-color: #212121;
        color: #757575;
        padding: 16px;
        min-height: 400px;
        height: auto;
      }
      vaadin-combo-box {
        --primary-text-color: gray;
        --secondary-text-color: gray;
        color: gray;
      }
      .div-component{
        width: 100%;
        height: 400px;
      }
      paper-material {
        background: white;
        width: 100%;
        height: 400px;
      }
    </style>
    <iron-ajax
			verbose
			auto
	    url="https://xxx.net/api/BlogEntries"
	    method='GET'
	    handle-as = "json"
	    content-type = 'application/json'
	    on-response="handleBlogEntryGet"
	    debounce-duration="300"
      on-error = 'handleBlogEntryGetError'
	    id='daoBlogEntry'>
		</iron-ajax>
    <iron-ajax
			verbose
			auto
	    url="https://xxxx.net/api/BlogCategories"
	    method='GET'
	    handle-as = "json"
	    content-type = 'application/json'
	    on-response="handleBlogCategoryGet"
	    debounce-duration="300"
      on-error = 'handleBlogCategoryGetError'
	    id='daoBlogCategory'>
		</iron-ajax>
    <iron-ajax
			verbose
      body="{{entry}}"
	    handle-as="json"
	    content-type="application/x-www-form-urlencoded"
	    on-response="handleSubmitEntry"
	    debounce-duration="300"
      on-error = 'handleSubmitEntryError'
	    id='daoSubmitEntry'>
		</iron-ajax>
    <iron-localstorage name="signasafeAdmStorage" id="admStorageId" value="{{sessionObject}}"></iron-localstorage>
    <div class="div-general">
      <div class="div-right">
        <div class="div-header">
						<paper-toolbar>
							<iron-icon icon="icons:list"></iron-icon>
						  	<div class="title">Entries</div>
						  	<span class="space"></span>
					        
					        <paper-icon-button icon="refresh" id="btRefresh" on-tap="handleRefresh"></paper-icon-button>
					        <paper-spinner id="spinner"></paper-spinner>
						</paper-toolbar>
					</div>
          <div class='div-list-content'>
							<template is="dom-repeat" items="{{entries}}">
                <div class="card" on-tap="handleEntryTap">
                  <paper-ripple></paper-ripple>
                  <div class="div-left-side">
                    <iron-icon icon="icons:description"></iron-icon>
                  </div>
                  <div class="div-text-side">
                    <span>{{item.BlogEntryTitle}}</span>
                  </div>
                  <div class="div-right-side">
                    <paper-icon-button icon="icons:clear" id="btDelete" on-tap="handleDeleteEntry"></paper-icon-button>
                  </div>
                </div>
					  	</template>
					</div>
      </div>
      <div class="div-left">
        <div class="div-header">
          <paper-toolbar>
  					<iron-icon icon="editor:border-color"></iron-icon>
  				  	<div class="title">Form Entry</div>
  				  	<span class="space"></span>
  			        
                <paper-icon-button icon="add" id="btFormAdd" on-tap="handleAddTap"></paper-icon-button>
					      <paper-icon-button icon="save" id="btFormSave" on-tap="handleSaveTap"></paper-icon-button>
					      <paper-spinner id="spinnerForm" hidden></paper-spinner>
  				</paper-toolbar>
        </div>
        <div class="card-content" id="divGeneral">
          <paper-input label="Id" value="{{entry.Id}}" id="tbEntryId" readonly></paper-input>
          <paper-input label="Date (yyyy-MM-dd)" id="entryDatePicker" required auto-validate error-message="Please fill out this field." type="date"></paper-input>
					<paper-input label="Title" value="{{entry.BlogEntryTitle}}" id="tbEntryTitle" required auto-validate error-message="Please fill out this field."></paper-input>
          <span>Published? <paper-toggle-button checked={{entry.BlogEntryPublished}}></paper-toggle-button></span>
          <paper-input label="Published By" value="{{entry.BlogEntryPublishedBy}}" id="tbPublishedBy" readonly></paper-input>
					<paper-textarea label="Write summary for the entry" char-counter maxlength="300" maxRows='2' required auto-validate charCounter error-message="Please fill out this field." value="{{entry.BlogEntrySummary}}" id="tbSummary"></paper-textarea>
					<vaadin-combo-box class="elements-box" label="Category" items="[[categories]]" item-label-path="BlogCategoryName" item-value-path="Id" id="cbCategory" required></vaadin-combo-box>
					<p>Entry content:</p>
          <div class="div-component">
            <paper-material elevation="5">
              <wysiwyg-e class="flex fit" value="{{entry.BlogEntryContent}}" id="wysiwygE">
                <wysiwyg-tool-bold class="wysiwyg-tool"></wysiwyg-tool-bold>
                <wysiwyg-tool-italic class="wysiwyg-tool"></wysiwyg-tool-italic>
                <wysiwyg-tool-underline class="wysiwyg-tool"></wysiwyg-tool-underline>
                <wysiwyg-tool-strike class="wysiwyg-tool"></wysiwyg-tool-strike>
                <wysiwyg-tool-clear class="wysiwyg-tool"></wysiwyg-tool-clear>
                <wysiwyg-tool-link class="wysiwyg-tool"></wysiwyg-tool-link>
                <wysiwyg-tool-image class="wysiwyg-tool"></wysiwyg-tool-image>
                <wysiwyg-tool-ordered class="wysiwyg-tool"></wysiwyg-tool-ordered>
                <wysiwyg-tool-unordered class="wysiwyg-tool"></wysiwyg-tool-unordered>
                <wysiwyg-tool-indent class="wysiwyg-tool"></wysiwyg-tool-indent>
                <wysiwyg-tool-outdent class="wysiwyg-tool"></wysiwyg-tool-outdent>
                <wysiwyg-tool-justify class="wysiwyg-tool" right center full></wysiwyg-tool-justify>
                <wysiwyg-tool-heading class="wysiwyg-tool" h1 h2 h3 h4 h5 h6></wysiwyg-tool-heading>
                <wysiwyg-tool-blockquote class="wysiwyg-tool"></wysiwyg-tool-blockquote>
                <wysiwyg-tool-undo class="wysiwyg-tool"></wysiwyg-tool-undo>
                <wysiwyg-tool-redo class="wysiwyg-tool"></wysiwyg-tool-redo>
    					</wysiwyg-e>
            </paper-material>
          </div>
        </div>
      </div>
    </div>
    <paper-toast id="toastMsg" class="fit-bottom"></paper-toast>
  </template>
  <script>
    Polymer({
      is: 'my-blogentry',
      properties:{
        sessionObject:{
           type: Object,
           notify: true
        },
        entries:{
          type: Object,
		      notify: true,
		      value: function() { return [ ]; }
        },
        entry:{
          type: Object,
		      notify: true,
		      value: function(){ return { Id: 0, BlogEntryDate: "", BlogEntryTitle: "", BlogEntrySummary: "", BlogEntryContent: "", BlogEntryPublishedBy: "", BlogEntryPublished: false, BlogCategoryId: 0}; }
        },
        categories:{
          type:Object,
        }
      },
      ready:function(){
        this.$.btRefresh.hidden = true;
        this.$.spinner.active = true;
        this.$.spinner.hidden = false;
        var objs = this.$$('#divGeneral');
        this.$.toastMsg.fitInto = objs;
        this.$$('#admStorageId').reload();
        this.$.tbPublishedBy.value = this.sessionObject.userName;
        this.$.entryDatePicker.value = moment(new Date()).format("YYYY-MM-DD");
      },
      handleBlogEntryGet: function(request){
        var result = request.detail.response;
				this.entries = result;
        this.$.btRefresh.hidden = false;
        this.$.spinner.active = false;
        this.$.spinner.hidden = true;
      },
      handleBlogEntryGetError: function(error){
        this.$.spinner.hidden = true;
        this.$.spinner.active = false;
        this.$.btRefresh.hidden = false;
        this.$.toastMsg.text = error;
        this.$.toastMsg.show();
      },
      handleRefresh: function(event, detail, sender){
        this.$.btRefresh.hidden = true;
        this.$.spinner.active = true;
        this.$.spinner.hidden = false;
        this.$.daoBlogEntry.generateRequest();
      },
      handleBlogCategoryGet: function(request){
        var result = request.detail.response;
        this.categories = result;
      },
      handleBlogCategoryGetError: function(error){
        this.$.toastMsg.text = error;
        this.$.toastMsg.show();
      },
      handleAddTap: function(event, detail, sender){
        this.entry = { Id: 0, BlogEntryDate: "", BlogEntryTitle: "", BlogEntrySummary: "", BlogEntryContent: "", BlogEntryPublishedBy: this.sessionObject.userName, BlogEntryPublished: false, BlogCategoryId: 0};
        this.$.entryDatePicker.value = moment(new Date()).format("YYYY-MM-DD");
      },
      handleSaveTap: function(event, detail, sender){
        this.$.spinnerForm.active = true;
        this.$.spinnerForm.hidden = false;
        var entryDatePicker = this.$.entryDatePicker;
        var tbEntryTitle = this.$.tbEntryTitle;
        var cbCategory = this.$.cbCategory;
        var tbSummary = this.$.tbSummary;
        this.entry.BlogCategoryId = cbCategory.value;
        this.entry.BlogEntryDate = entryDatePicker.value;
        if(entryDatePicker.validate() && tbEntryTitle.validate() && tbSummary.validate() && this.entry.BlogCategoryId != 0){
          if(this.entry.Id == 0){
            this.$.daoSubmitEntry.url = "https://xxxx.net/api/BlogEntries";
            this.$.daoSubmitEntry.method = 'POST';
            this.$.daoSubmitEntry.headers = { "Authorization": "Bearer " + this.sessionObject.access_token };
            this.$.daoSubmitEntry.generateRequest();
          }else{
            this.$.daoSubmitEntry.url = "https://xxx.net/api/BlogEntries/" + this.entry.Id;
            this.$.daoSubmitEntry.method = 'PUT';
            this.$.daoSubmitEntry.headers = { "Authorization": "Bearer " + this.sessionObject.access_token };
            this.$.daoSubmitEntry.generateRequest();
          }
        }
      },
      handleSubmitEntry:function(request){
        this.$.spinnerForm.active = false;
        this.$.spinnerForm.hidden = true;
        this.$.daoBlogEntry.generateRequest();
        var result = request.detail.response;
        this.entry = { Id: 0, BlogEntryDate: "", BlogEntryTitle: "", BlogEntrySummary: "", BlogEntryContent: "", BlogEntryPublishedBy: this.sessionObject.userName, BlogEntryPublished: false, BlogCategoryId: 0};
        this.$.toastMsg.text = "The entry was saved successfully";
        this.$.toastMsg.show();
      },
      handleSubmitEntryError: function(error){
        this.$.toastMsg.text = error;
        this.$.toastMsg.show();
      },
      handleEntryTap: function(event, detail, sender){
        this.entry = event.model.item;
        var date = new Date(this.entry.BlogEntryDate);
        this.$.entryDatePicker.value = moment(date).format("YYYY-MM-DD");
        this.$.cbCategory.value = this.entry.BlogCategoryId;
      },
      handleDeleteEntry: function(event, detail, sender){
        this.$.daoSubmitEntry.url = "https://xxxx.net/api/BlogEntries/" + event.model.item.Id;
        this.$.daoSubmitEntry.method = 'DELETE';
        this.$.daoSubmitEntry.headers = { "Authorization": "Bearer " + this.sessionObject.access_token };
        this.$.daoSubmitEntry.generateRequest();
      }
    });
  </script>
</dom-module>`

**Comment by miztroh** [comment]
Thanks for your .gifs.  It helps to see that the issue is limited to your context.  If you can host your code somewhere I can actually use it, I'll be happy to take a look.

**Comment by jperera84** [comment]
@miztroh , thank you so much, I'm going to upload to githup so you could take a look.

**Comment by jperera84** [comment]
@miztroh, this is the project and the url for the element that it is using the component, please let me know when you finish to delete the project, thanks
https://github.com/jperera84/signasafe-admin/blob/master/src/my-blogentry.html

**Comment by miztroh** [comment]
@jperera84 I was just looking to demo the page itself.  Can you email me a link to a demo site?
