### ISSUE TITLE
Is there undocumented way to add code tag

### ISSUE THREAD

**Issue by hyyan** [miztroh/wysiwyg-e#83]
Hello

I was wondering if Is there undocumented way to add code tag , before I dig more in the code to add such a feature if not exist yet

Thanks in advance

**Comment by hyyan** [comment]
As I can see in the demo there is already a code tag , but not clear how to add it

**Comment by miztroh** [comment]
It is not currently possible via the interface to insert a code tag.  There is an open ticket regarding the code tag: https://github.com/miztroh/wysiwyg-e/issues/51

My plan is to take care of some of the more urgent issues and important enhancements, then circle back to the code tag.   Of course, pull requests are always welcome :)

**Comment by hyyan** [comment]
Sure , I understand , I am working on this tool now , I will send a PR whenever it is ready.

Thanks for the great job  :)
