### ISSUE TITLE
Is it safe to rely on `document.getSelection()`

### ISSUE THREAD

**Issue by hyyan** [miztroh/wysiwyg-e#84]
Is it safe to rely on `document.getSelection()` or there is a replacement method ?

**Comment by miztroh** [comment]
``wysiwyg-e`` is built on functionality from https://github.com/miztroh/selection-mgr/, so you can use something like ``wysiwygE_instance.getSelection();``.

**Comment by hyyan** [comment]
I see , but what is the way to get the wysiwygE_instance within the tool ?

**Comment by miztroh** [comment]
``wysiwygE_instance`` is a variable name I made up to reference the ``wysiwyg-e`` element instance.  For example: ``document.querySelector('wysiwyg-e').getSelection();``.

**Comment by hyyan** [comment]
I see  ... 

Thanks for the fast help
