### ISSUE TITLE
space key is acting strange

### ISSUE THREAD

**Issue by jay8t6** [miztroh/wysiwyg-e#92]
When I enter a space for the first time, the cursor moves back to the beginning of the sentence. This is also happening in your demo file. Can you get this fixed?

**Comment by miztroh** [comment]
What operating system and browser are you using?

**Comment by jay8t6** [comment]
Its chrome 52. Latest version. I just checked Safari 9.1.1, its happening there too.

**Comment by miztroh** [comment]
Confirmed in Chrome and Safari on OS X El Capitan.

**Comment by jay8t6** [comment]
same thing happens when you press the return key

**Comment by joeblew99** [comment]
me too
chrome latest on osx

**Comment by miztroh** [comment]
@joeblew99 @jay8t6 Can you confirm this fixes it for you?

**Comment by jay8t6** [comment]
@miztroh yes the space issue is fixed. Thanks!
