### ISSUE TITLE
backspace problem

### ISSUE THREAD

**Issue by robrez** [miztroh/wysiwyg-e#97]
I'm having trouble w/ backspace when `value` an empty string

Haven't had a lot of time to play around, but it seems I can workaround by defaulting value to `<p><br/></p>`

**Comment by robrez** [comment]
Not sure if this is right, but I patched the _backspace function...

```javascript
        _backspace: function () {
          if (this.target.children.length > 1) {
            document.execCommand('delete');
          } else if (this.target.children.length === 1) {
            if (this.target.children[0].textContent.length) {
              document.execCommand('delete');
            } else {
              document.execCommand('formatBlock', null, 'P');
            }
+         } else if (this.target.textContent.length) {
+           document.execCommand('delete');
          }
        },
```

I also noticed that backspace was not working in the input fields provided by some of the tools, eg: link.

I patched _kedown..
```javascript
_keydown: function (event) {
+   if (Polymer.dom(event).rootTarget.id !== "editable") {
+     return;
+   }
    //Prevent default delete **behavior**
    ...
}
```

**Comment by miztroh** [comment]
Thanks for the report.  Only needed to check the source of the event against the editing target.

```
_keydown: function (event) {
   if (!this.target.contains(event.target)) return;
   ...
}
```

**Comment by robrez** [comment]
Thanks for the fix! still wondering about the 1st of the two problems I mentioned (regarding backspace/delete in the _backspace function)

**Comment by miztroh** [comment]
That is actually a separate issue that I needed to guard against in the ``sanitize`` function.  See #100.
